//{{NO_DEPENDENCIES}}
// Plik do³¹czany wygenerowany przez œrodowisko Microsoft Visual C++.
// U¿ywany przez: AtumLauncher.rc
//
#define IDR_MANIFEST                    1
#define ID_SAVE                         4
#define IDM_ABOUTBOX                    0x0010
#define RT_MANIFEST                     24
#define IDS_ABOUTBOX                    101
#define IDD_ATUMLAUNCHER_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDB_LOGIN                       158
#define IDB_UPDATE                      195
#define IDB_BACKIMAGE                   210
#define IDB_X                           214
#define IDB_GEAR                        221
#define IDB_SERVERLIST                  222
#define IDB_USECLASS                    223
#define IDB_BARLEFT                     224
#define IDB_BARRIGHT                    225
#define IDB_BARCENTER                   226
#define IDB_GOD                         234
#define IDB_GOBTN                       235
#define IDB_JOINBTN                     240
#define IDB_CENTER                      241
#define IDB_TITLE                       242
#define IDB_SERVERUSER                  247
#define IDB_BG_VTC                      248
#define IDB_GO_VTC                      249
#define IDB_LISTBG_VTC                  250
#define IDB_ICON_VTC                    251
#define IDB_SERVERUSER_VTC              252
#define IDB_GO_S2                       255
#define IDB_GO_CHN                      257
#define IDD_DIALOG1                     259
#define IDB_SCREEN_KEYBOARD             260
#define IDB_SCREEN_KEYBOARD_MASK        261
#define IDB_SCREEN_KEYBOARD_ON_SHIFT    262
#define IDB_KEY_1                       263
#define IDB_KEY_2                       264
#define IDB_KEY_3                       265
#define IDB_KEY_4                       266
#define IDB_KEY_5                       267
#define IDB_KEY_6                       268
#define IDB_KEY_7                       269
#define IDB_KEY_8                       270
#define IDB_KEY_9                       271
#define IDB_KEY_0                       272
#define IDB_KEY_q                       273
#define IDB_KEY_w                       274
#define IDB_KEY_e                       275
#define IDB_KEY_r                       276
#define IDB_KEY_t                       277
#define IDB_KEY_y                       278
#define IDB_KEY_u                       279
#define IDB_KEY_i                       280
#define IDB_KEY_o                       281
#define IDB_KEY_p                       282
#define IDB_KEY_a                       283
#define IDB_KEY_s                       284
#define IDB_KEY_d                       285
#define IDB_KEY_f                       286
#define IDB_KEY_g                       287
#define IDB_KEY_h                       288
#define IDB_KEY_j                       289
#define IDB_KEY_k                       290
#define IDB_KEY_l                       291
#define IDB_KEY_z                       292
#define IDB_KEY_x                       293
#define IDB_KEY_c                       294
#define IDB_KEY_v                       295
#define IDB_KEY_b                       296
#define IDB_KEY_n                       297
#define IDB_KEY_m                       298
#define IDB_KEY_1_ON_SHIFT              299
#define IDB_KEY_2_ON_SHIFT              300
#define IDB_KEY_3_ON_SHIFT              301
#define IDB_KEY_4_ON_SHIFT              302
#define IDB_KEY_5_ON_SHIFT              303
#define IDB_KEY_6_ON_SHIFT              304
#define IDB_KEY_7_ON_SHIFT              305
#define IDB_KEY_8_ON_SHIFT              306
#define IDB_KEY_9_ON_SHIFT              307
#define IDB_KEY_0_ON_SHIFT              308
#define IDB_KEY_q_ON_SHIFT              309
#define IDB_KEY_w_ON_SHIFT              310
#define IDB_KEY_e_ON_SHIFT              311
#define IDB_KEY_r_ON_SHIFT              312
#define IDB_KEY_t_ON_SHIFT              313
#define IDB_KEY_y_ON_SHIFT              314
#define IDB_KEY_u_ON_SHIFT              315
#define IDB_KEY_i_ON_SHIFT              316
#define IDB_KEY_o_ON_SHIFT              317
#define IDB_KEY_p_ON_SHIFT              318
#define IDB_KEY_a_ON_SHIFT              319
#define IDB_KEY_s_ON_SHIFT              320
#define IDB_KEY_d_ON_SHIFT              321
#define IDB_KEY_f_ON_SHIFT              322
#define IDB_KEY_g_ON_SHIFT              323
#define IDB_KEY_h_ON_SHIFT              324
#define IDB_KEY_j_ON_SHIFT              325
#define IDB_KEY_k_ON_SHIFT              326
#define IDB_KEY_l_ON_SHIFT              327
#define IDB_KEY_z_ON_SHIFT              328
#define IDB_KEY_x_ON_SHIFT              329
#define IDB_KEY_c_ON_SHIFT              330
#define IDB_KEY_v_ON_SHIFT              331
#define IDB_KEY_b_ON_SHIFT              332
#define IDB_KEY_n_ON_SHIFT              333
#define IDB_KEY_m_ON_SHIFT              334
#define IDB_KEY_BACKSPACE               335
#define IDB_KEY_CAPSLOCK                336
#define IDB_KEY_ENTER                   337
#define IDB_KEY_SHIFT                   338
#define IDB_KEY_SPACE                   339
#define IDB_KEY_CAPSLOCK_ON             340
#define IDB_KEY_SHIFT_ON                341
#define IDB_HOMEPAGE_DOWN               342
#define IDB_HOMEPAGE_FOCUS              343
#define IDB_HOMEPAGE_UP                 344
#define IDB_EDITBG                      346
#define IDB_CB_CHECK                    348
#define IDB_CB_UNCHECK                  349
#define IDB_COMBOBOX                    350
#define IDB_REPAIR_BUT                  355
#define IDB_SETTINGS_BUTT               356
#define IDB_BG_VTC_MASK                 357
#define INET_KBC_CLOSE                  358
#define INET_KBC_MINIM                  359
#define IDB_TITLE_MASK                  361
#define IDB_SERVER_LIST_MASK            365
#define IDD_INET_CONFIG                 366
#define IDB_CFG_BK                      367
#define IDB_POPUP_CLOSE                 368
#define IDC_EDIT_ACCOUNT                1002
#define IDC_ACCOUNT                     1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_PASSWORD                    1005
#define IDC_LOGO                        1006
#define IDC_DOWNLOAD_FILENUM            1007
#define IDC_DECA_SERVER                 1008
#define IDC_PLAYER_CNT                  1008
#define IDC_PROGRESS1                   1009
#define IDC_FILE_UPDATE_GROUP           1010
#define IDC_DOWNLOAD_FILENUM2           1010
#define IDC_NOTICE2                     1010
#define IDC_BATTALUS_SERVER             1011
#define IDC_SHARRINE_SERVER             1012
#define IDC_PHILON_SERVER               1013
#define IDC_STATIC_SERVER_GROUP         1014
#define IDC_EDIT_PRE_IP                 1016
#define IDGO                            1019
#define IDC_EDIT_BIN                    1020
#define IDC_NOTICE                      1020
#define IDJOIN                          1021
#define IDSECRET                        1022
#define IDC_EDIT_PATH                   1022
#define IDEND                           1023
#define IDDECA                          1024
#define IDBATTAL                        1025
#define IDSHARIN                        1026
#define IDPHILON                        1027
#define IDC_BUTTON3                     1030
#define IDC_X                           1030
#define IDC_FILE_INFO                   1031
#define IDC_STATIC_WINDOW_DEGREE        1037
#define IDC_LIST                        1038
#define IDC_COMBO                       1045
#define IDC_COMBO_WINDOW_DEGREE_LAUNCHER 1045
#define IDC_COMBO_WINDOW_DEGREE_LAUNCHER2 1046
#define IDCAN                           1048
#define IDMIN                           1049
#define IDC_BTN_HOMEPAGE                1050
#define IDREP                           1051
#define IDC_CHARACTER_NAME              1052
#define IDC_COMBO_SERVER_LIST           1054
#define IDC_BTN_VIEW_SCREEN_KEYBOARD    1093
#define IDC_CHECK_WINDOWS_MODE          1094
#define IDC_CHECK_REMEMBER_ID           1095
#define IDC_CHECK_WINDOWS_MODE2         1096
#define IDC_VSYNC                       1096
#define IDC_CHECK_64_BIT                1096
#define IDC_EDIT_AGREEMENT_TEXT         1097
#define IDC_BTN_VIEW_INET_CFG           1097
#define IDC_STATIC5                     1098
#define IDC_COMBO1                      1099
#define IDC_COMBO_LANG                  1099
#define IDC_AA_LV                       1099
#define IDC_CHECK_FPS                   1100
#define IDC_AA_QTY                      1101
#define IDC_CHECK2                      1102
#define IDC_CHECK_PASS                  1102
#define IDC_TEX_FLT_TYPE                1103
#define IDC_ANISO_LV                    1104
#define IDC_STATIC1                     1105
#define IDC_STATIC2                     1106
#define IDC_STATIC3                     1107
#define IDC_STATIC4                     1108
#define IDCANCEL_POPUP                  1109
#define IDC_STATIC6                     1110
#define IDC_DIS_PARAL                   1111
#define IDC_RADIO1                      1112
#define IDC_RADIO2                      1113
#define IDC_RADIO3                      1114
#define IDC_EDIT1                       1115
#define IDC_STATIC7                     1116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
