
// 2005-04-28 by cmkwon
// #include "StringDefineServer.h"
#ifndef _STRING_DEFINE_SERVER_H_
#define _STRING_DEFINE_SERVER_H_

#include "StringDefineCommon.h"


///////////////////////////////////////////////////////////////////////////////
// 1 Atum
	// 1-1 
	#define STRERR_S_ATUMEXE_0001 "sunucu değil activated. \r\nPlease remember -e right click -> Run as yönetici!"
	#define STRERR_S_ATUMEXE_0002 "Socket kapalı tarafından Pre sunucu!"
	#define STRERR_S_ATUMEXE_0003 "Auto update başarısız.\r\nPlease reinstall game.\r\n"
	#define STRERR_S_ATUMEXE_0004 "hata %s(%#04X) alındı -den %s[%s]\r\n"
	#define STRERR_S_ATUMEXE_0005 "bilinmeyen hata: %s(%#04x)"
	#define STRERR_S_ATUMEXE_0006 "Cannot connect -e download sunucu."
	#define STRERR_S_ATUMEXE_0007 "Download files size bilinmeyen."
	#define STRERR_S_ATUMEXE_0008 "Update dosya cannot be downloaded."
	#define STRERR_S_ATUMEXE_0009 "sistem out bellek veya resources."
	#define STRERR_S_ATUMEXE_0010 ".exe dosya geçersiz."
	#define STRERR_S_ATUMEXE_0011 "dosya değil found."
	#define STRERR_S_ATUMEXE_0012 "specified path değil found."
// 2006-04-20 by cmkwon, 	#define STRERR_S_ATUMEXE_0013 "[Error]Unknown Message Type: %d(0x%08X)\n"
// 1_end
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// 2 - AtumLauncher
	// 2-1 STRMSG
	#define STRMSG_S_ATUMLAUNCHER_0000 "Update complete"
	#define STRMSG_S_ATUMLAUNCHER_0001 "Please choose sunucu."
	#define STRMSG_S_ATUMLAUNCHER_0002 "Updating sil dosya List v%s\r\n"
	#define STRMSG_S_ATUMLAUNCHER_0003 "Deleting temporary files"
	#define STRMSG_S_ATUMLAUNCHER_0004 "Updating notice"
	#define STRMSG_S_ATUMLAUNCHER_0005 "Update complete(%s -> %s)"
	#define STRMSG_S_ATUMLAUNCHER_0006 "seç operation dosya"
	#define STRMSG_S_ATUMLAUNCHER_0007 "seç operation path"
	#define STRMSG_S_ATUMLAUNCHER_0008 "Downloading has been iptal edildi"
	#define STRMSG_S_ATUMLAUNCHER_0009 "Download finished"
	#define STRMSG_S_ATUMLAUNCHER_0010 "Updating -e v%s - %s(%d/%d)"
	#define STRMSG_S_ATUMLAUNCHER_0011 "yapılamıyor oluştur dosya %s"
	#define STRMSG_S_ATUMLAUNCHER_0012 "Updating -e v%s - %s(%d/%d)"
	#define STRMSG_S_ATUMLAUNCHER_0013 "Aquiring dosya bilgi %s"
	
	// STRERR
	#define STRERR_S_ATUMLAUNCHER_0000 "[hata] Parameter Count hata, Count(%d)\n"
	#define STRERR_S_ATUMLAUNCHER_0001 "[hata] Mutex hata\n"
	#define STRERR_S_ATUMLAUNCHER_0002 "[hata] Excute Type hata, Type(%s)\n"
	#define STRERR_S_ATUMLAUNCHER_0003 "[hata] Decryption ID hata, DecryptedID(%s)\n"
	#define STRERR_S_ATUMLAUNCHER_0004 "Cannot connect -e Pre sunucu."
	#define STRERR_S_ATUMLAUNCHER_0005 "başarısız oldu: connect -e sunucu."
	#define STRERR_S_ATUMLAUNCHER_0006 "Socket kapalı tarafından Pre sunucu!"
	#define STRERR_S_ATUMLAUNCHER_0007 "Notice dosya hata!"
	#define STRERR_S_ATUMLAUNCHER_0009 "Auto update başarısız.\r\nPlease reinstall game.\r\n"
	#define STRERR_S_ATUMLAUNCHER_0010 "tüm servers oluyor pasif bu zaman."
	#define STRERR_S_ATUMLAUNCHER_0011 "%-16s%s under examination..."
	#define STRERR_S_ATUMLAUNCHER_0012 "tüm servers oluyor under examination. Try logging içinde daha sonra."
	#define STRERR_S_ATUMLAUNCHER_0013 "hata %s(%#04X) alındı -den %s[%s]\r\n"
// 2006-05-26 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0014 "Wrong ID, password error\n\n* only people who are certified as beta tester can log in at the present."
//	#define STRERR_S_ATUMLAUNCHER_0014 "You have entered an invalid login ID or password.  Please enter a registered login ID and password."
	#define STRERR_S_ATUMLAUNCHER_0015 "hata içinde giriş process"
	#define STRERR_S_ATUMLAUNCHER_0016 "kullanıcı ID değil entered"
	#define STRERR_S_ATUMLAUNCHER_0017 "Double log içinde"
	#define STRERR_S_ATUMLAUNCHER_0018 "F sunucu değil executed."
	#define STRERR_S_ATUMLAUNCHER_0019 "I sunucu değil executed."
	#define STRERR_S_ATUMLAUNCHER_0020 "Sevice durduruldu temporarily.\n\nTry logging içinde daha sonra."
	#define STRERR_S_ATUMLAUNCHER_0021 "There oluyor too many users online.\n\nTry logging içinde daha sonra."
	#define STRERR_S_ATUMLAUNCHER_0022 "hesap şu anda blocked.\nPeriod: %s\n\nConatact Customer Support [https://support.oldschoolrivals.com/] içiçinde further details."
	#define STRERR_S_ATUMLAUNCHER_0023 "istemci version değil correct.\n\nPlease download game again."
	#define STRERR_S_ATUMLAUNCHER_0024 "hata: %s(%#04X)"
	#define STRERR_S_ATUMLAUNCHER_0025 "Cannot log içinde -e download sunucu."
	#define STRERR_S_ATUMLAUNCHER_0026 "Size download dosya(%s)cannot be known."
	#define STRERR_S_ATUMLAUNCHER_0027 "Size download dosya unknwon."
	#define STRERR_S_ATUMLAUNCHER_0028 "Cannot download update dosya."
	#define STRERR_S_ATUMLAUNCHER_0029 "Updated dosya does mevcut değil."
	#define STRERR_S_ATUMLAUNCHER_0030 "seçildi sunucu under examination. Try logging içinde daha sonra."
	#define STRERR_S_ATUMLAUNCHER_0031 "sistem out bellek veya resources."
	#define STRERR_S_ATUMLAUNCHER_0032 ".exe dosya geçersiz."
	#define STRERR_S_ATUMLAUNCHER_0033 "dosya bulunamıyor."
	#define STRERR_S_ATUMLAUNCHER_0034 "Path bulunamıyor."
// 2006-04-20 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0035 "[Error] Unhandled Message Type: %s(%#04X)\n"
// 2006-04-20 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0036 "[Error] Unhandled Message Type!\n"

	#define STRMSG_S_050506		"\'%s\'s hesap blocked presently.\n Reason: %s\n Period: %s~%s\n\nConatact Customer Support [https://support.oldschoolrivals.com] içiçinde further details."
	#define STRMSG_S_050930		"Please download game again.\nURL: [https://oldschoolrivals.com] %s\nNewest version:"
// 2_end
///////////////////////////////////////////////////////////////////////////////	

///////////////////////////////////////////////////////////////////////////////
// 3 - AtumAdminTool
	// 3-1 STRMSG
//	#define STRMSG_S_SCADMINTOOL_0000 "Male"
//	#define STRMSG_S_SCADMINTOOL_0001 "Female"
//	#define STRMSG_S_SCADMINTOOL_0002 "A.D%d, Age%d"
//	#define STRMSG_S_SCADMINTOOL_0003 "Do you really want to modify your account information?"
//	#define STRMSG_S_SCADMINTOOL_0004 "CAST(l.CurrentCount AS VARCHAR(10)) + 'piece'"
//	#define STRMSG_S_SCADMINTOOL_0005 "CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces attained, ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'piece'"
//	#define STRMSG_S_SCADMINTOOL_0006 "'''To ' + l.PeerCharacterName + ''', give ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
//	#define STRMSG_S_SCADMINTOOL_0007 "'''To ' + l.PeerCharacterName + ''', receive ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
//	#define STRMSG_S_SCADMINTOOL_0008 "'''Discard ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
//	#define STRMSG_S_SCADMINTOOL_0009 "CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces bought, remaining Spi: ' + CAST(l.RemainedMoney AS VARCHAR(10))"
//	#define STRMSG_S_SCADMINTOOL_0010 "CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces sold, remaining Spi: ' + CAST(l.RemainedMoney AS VARCHAR(10))"
//	#define STRMSG_S_SCADMINTOOL_0011 "CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
	#define STRMSG_S_SCADMINTOOL_0012 "'''' + l.PeerCharacterName + ''' eklendi ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
	#define STRMSG_S_SCADMINTOOL_0013 "'''' + l.PeerCharacterName + ''' silindi ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'piece'"
	#define STRMSG_S_SCADMINTOOL_0014 "'ekle ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
	#define STRMSG_S_SCADMINTOOL_0015 "'Deposit ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
	#define STRMSG_S_SCADMINTOOL_0016 "'Recover ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'pieces, total' + CAST(l.CurrentCount AS VARCHAR(10)) + 'pieces'"
	#define STRMSG_S_SCADMINTOOL_0017 "\'game zaman \' + dbo.atum_GetHMSFromS(l.PlayTime) + \', whole \' + dbo.atum_GetHMSFromS(l.TotalPlayTime)"
	#define STRMSG_S_SCADMINTOOL_0018 "CAST(l.Param1 AS VARCHAR(10)) + ' -> ' + CAST(l.Param2 AS VARCHAR(10)) + ', game zaman: ' + dbo.atum_GetHMSFromS(l.Param3)"
//	#define STRMSG_S_SCADMINTOOL_0019 "CAST(l.Param1 AS VARCHAR(15)) + \' rise and fall, whole \' + CAST(l.Param2 AS VARCHAR(15))"
//	#define STRMSG_S_SCADMINTOOL_0020 "Crash"
//	#define STRMSG_S_SCADMINTOOL_0021 "Monster"
//	#define STRMSG_S_SCADMINTOOL_0022 "GEAR"
//	#define STRMSG_S_SCADMINTOOL_0023 "Reason unknown"
//	#define STRMSG_S_SCADMINTOOL_0024 "%s, Remaining stat: %s"
	#define STRMSG_S_SCADMINTOOL_0025 "(Do mevcut değil)"
//	#define STRMSG_S_SCADMINTOOL_0026 "myself"
//	#define STRMSG_S_SCADMINTOOL_0027 "Does not exist"
//	#define STRMSG_S_SCADMINTOOL_0028 "User with bug use"
	#define STRMSG_S_SCADMINTOOL_0029 "hesap blocked"
	#define STRMSG_S_SCADMINTOOL_0030 "sohbet prohibited"
//	#define STRMSG_S_SCADMINTOOL_0031 "Connection log"
//	#define STRMSG_S_SCADMINTOOL_0032 "User log"
//	#define STRMSG_S_SCADMINTOOL_0033 "Item log"
	#define STRMSG_S_SCADMINTOOL_0034 "%s - %s sunucu"
	#define STRMSG_S_SCADMINTOOL_0035 "%s - %s sunucu,%d(%d)"
	#define STRMSG_S_SCADMINTOOL_0036 "hesap seized"
//	#define STRMSG_S_SCADMINTOOL_0037 "Classification    "
//	#define STRMSG_S_SCADMINTOOL_0038 "Value"
	#define STRMSG_S_SCADMINTOOL_0039 "istiyor musunuz unblock bu hesap?"
	#define STRMSG_S_SCADMINTOOL_0040 "%s(%dsaniye)"
	#define STRMSG_S_SCADMINTOOL_0041 "%dwin %dlost"
	#define STRMSG_S_SCADMINTOOL_0042 "bunu yapmak istediğinizden emin misiniz disconnect ve block hesap?"
	#define STRMSG_S_SCADMINTOOL_0043 "%s eşya"
	#define STRMSG_S_SCADMINTOOL_0044 "[%s %15s] Notice: %s\r\n"
	#define STRMSG_S_SCADMINTOOL_0045 "sayı users: %d\r\n"
	#define STRMSG_S_SCADMINTOOL_0046 "[%s %15s] alındı mesaj: %s\r\n"
	#define STRMSG_S_SCADMINTOOL_0047 "[%s %15s] sayı users: %4d\r\n"
	#define STRMSG_S_SCADMINTOOL_0048 "[%s %15s] FieldServer state: %d\r\n"
	#define STRMSG_S_SCADMINTOOL_0049 "bağlantı -e sunucu has been lost\nSocket isim: %s\nIP: %s"
	
	// 3-2 AtumAdminTool - STRERR
	#define STRERR_S_SCADMINTOOL_0000 "Cannot yükle ilgili hesap bilgi."
	#define STRERR_S_SCADMINTOOL_0001 "başarısız oldu: modify hesap bilgi."
	#define STRERR_S_SCADMINTOOL_0002 "gir sizin şifre"
	#define STRERR_S_SCADMINTOOL_0003 "şifre authentication başarısız"
	#define STRERR_S_SCADMINTOOL_0004 "gir log içinde isim"
	#define STRERR_S_SCADMINTOOL_0005 "Pre sunucu değil executed."
	#define STRERR_S_SCADMINTOOL_0006 "-ebilir değil connect -e PreServer!!"
//	#define STRERR_S_SCADMINTOOL_0007 "인증 실패하였습니다"			// 2006-04-11 by cmkwon, 주석처리함
	#define STRERR_S_SCADMINTOOL_0008 "hata: ilgili protocol does mevcut değil."
	#define STRERR_S_SCADMINTOOL_0009 "gir kullanıcı isim"
	#define STRERR_S_SCADMINTOOL_0010 "gir reason"
	#define STRERR_S_SCADMINTOOL_0011 "deneyim point set up hata: seviye %2d ==> Exp(%.1I64f ~ %.1I64f)"
	#define STRERR_S_SCADMINTOOL_0012 "maksimum log sayı exceeded.\r\n\r\nPlease modify sayı maksimum log veya search condition."
	#define STRERR_S_SCADMINTOOL_0013 "Cannot connect -e veritabanı."
	#define STRERR_S_SCADMINTOOL_0014 "değil bağlandı"
	#define STRERR_S_SCADMINTOOL_0015 "Connected"
	#define STRERR_S_SCADMINTOOL_0016 "Updating"
	#define STRERR_S_SCADMINTOOL_0017 "giriş yapıldı"
	#define STRERR_S_SCADMINTOOL_0018 "Choosing karakter"
	#define STRERR_S_SCADMINTOOL_0019 "Playing game"
	#define STRERR_S_SCADMINTOOL_0020 "Unknown"
	#define STRERR_S_SCADMINTOOL_0021 "veritabanı %s(%s:%d)cannot be bağlandı."
	#define STRERR_S_SCADMINTOOL_0022 "başarısız oldu: ekle eşya"
	#define STRERR_S_SCADMINTOOL_0023 "başarısız oldu: find blocked hesap."
	#define STRERR_S_SCADMINTOOL_0024 "First, disconnect -den hesap ve block it -e modify."
	#define STRERR_S_SCADMINTOOL_0025 "SPI(money) cannot be eklendi."
	#define STRERR_S_SCADMINTOOL_0026 "seçildi eşya zaten exists, so modify miktar."
	#define STRERR_S_SCADMINTOOL_0027 "hata finding eşya"
	#define STRERR_S_SCADMINTOOL_0028 "SPI(money) possessed tarafından karakter silinemez."
	#define STRERR_S_SCADMINTOOL_0029 "istiyor musunuz sil bu eşya?"
	#define STRERR_S_SCADMINTOOL_0030 "başarısız oldu: sil eşya."
	#define STRERR_S_SCADMINTOOL_0031 "başarısız oldu: modify eşya."
	#define STRERR_S_SCADMINTOOL_0032 "gir hesap"
	#define STRERR_S_SCADMINTOOL_0033 "hesap does mevcut değil.(hesap may possibly be blocked)"
	#define STRERR_S_SCADMINTOOL_0034 "hesap veya karakter does mevcut değil."
	#define STRERR_S_SCADMINTOOL_0035 "hata içinde karakter bilgi search."
	#define STRERR_S_SCADMINTOOL_0036 "ilgili karakter does mevcut değil"
	#define STRERR_S_SCADMINTOOL_0037 "hata içinde karakter update."
	#define STRERR_S_SCADMINTOOL_0038 "karakter bilgi güncellendi succesfully."
	#define STRERR_S_SCADMINTOOL_0039 "Choose eşya."
	#define STRERR_S_SCADMINTOOL_0040 "Choose sayı eşya."
	#define STRERR_S_SCADMINTOOL_0041 "ilgili eşya -ebilir be oluşturuldu under 5 pieces."
	#define STRERR_S_SCADMINTOOL_0042 "gir mesaj."
	#define STRERR_S_SCADMINTOOL_0043 "Notice cannot be sent."
	#define STRERR_S_SCADMINTOOL_0044 "%s: sunucu state(%d)\r\n"
	#define STRERR_S_SCADMINTOOL_0045 "IM sunucu değil executed."
	#define STRERR_S_SCADMINTOOL_0046 "Field sunucu değil executed."
	#define STRERR_S_SCADMINTOOL_0047 "[%s %15s] IMServer state: %d\r\n"

	// 3-3 AtumLaAtumAdminTool -
//	#define STRMSG_S_SCAT_COLNAME_0000 "Account name"
//	#define STRMSG_S_SCAT_COLNAME_0001 "Type"
//	#define STRMSG_S_SCAT_COLNAME_0002 "Conviction"
//	#define STRMSG_S_SCAT_COLNAME_0003 "Start date"
//	#define STRMSG_S_SCAT_COLNAME_0004 "Finish date"
//	#define STRMSG_S_SCAT_COLNAME_0005 "Handling person"
//	#define STRMSG_S_SCAT_COLNAME_0006 "Handling reason"
//	#define STRMSG_S_SCAT_COLNAME_0007 "Date"
//	#define STRMSG_S_SCAT_COLNAME_0008 "Log type"
//	#define STRMSG_S_SCAT_COLNAME_0009 "IPAddress"
//	#define STRMSG_S_SCAT_COLNAME_0010 "Server name"
//	#define STRMSG_S_SCAT_COLNAME_0011 "Character name"
//	#define STRMSG_S_SCAT_COLNAME_0012 "Location"
//	#define STRMSG_S_SCAT_COLNAME_0013 "Contents"
//	#define STRMSG_S_SCAT_COLNAME_0014 "Item"
//	#define STRMSG_S_SCAT_COLNAME_0015 "UID"
//	#define STRMSG_S_SCAT_COLNAME_0016 "Own number"
//	#define STRMSG_S_SCAT_COLNAME_0017 "Name"
//	#define STRMSG_S_SCAT_COLNAME_0018 "Item number"
//	#define STRMSG_S_SCAT_COLNAME_0019 "Prefix"
//	#define STRMSG_S_SCAT_COLNAME_0020 "Suffix"
	#define STRMSG_S_SCAT_COLNAME_0021 "Equip"
//	#define STRMSG_S_SCAT_COLNAME_0022 "Amount"
//	#define STRMSG_S_SCAT_COLNAME_0023 "Endurance"
//	#define STRMSG_S_SCAT_COLNAME_0024 "Create time"
	#define STRMSG_S_SCAT_COLNAME_0025 "değil kuşanıldı"
//	#define STRMSG_S_SCAT_COLNAME_0026 "Warehouse"
//	#define STRMSG_S_SCAT_COLNAME_0027 "Auction"
//	#define STRMSG_S_SCAT_COLNAME_0028 "Map"
//	#define STRMSG_S_SCAT_COLNAME_0029 "Coordinate"
//	#define STRMSG_S_SCAT_COLNAME_0030 "Sex"
//	#define STRMSG_S_SCAT_COLNAME_0031 "Race"
//	#define STRMSG_S_SCAT_COLNAME_0032 "Authority"
//	#define STRMSG_S_SCAT_COLNAME_0033 "Unit kind"
//	#define STRMSG_S_SCAT_COLNAME_0034 "Level"
//	#define STRMSG_S_SCAT_COLNAME_0035 "Maximum level"
//	#define STRMSG_S_SCAT_COLNAME_0036 "Experience point"
//	#define STRMSG_S_SCAT_COLNAME_0037 "Decreased experience point"
//	#define STRMSG_S_SCAT_COLNAME_0038 "Auto stat division type"
//	#define STRMSG_S_SCAT_COLNAME_0039 "Attack"
//	#define STRMSG_S_SCAT_COLNAME_0040 "Defense"
//	#define STRMSG_S_SCAT_COLNAME_0041 "Fuel"
//	#define STRMSG_S_SCAT_COLNAME_0042 "Spirit"
//	#define STRMSG_S_SCAT_COLNAME_0043 "Shield"
//	#define STRMSG_S_SCAT_COLNAME_0044 "Agility"
//	#define STRMSG_S_SCAT_COLNAME_0045 "Attached regiment"
//	#define STRMSG_S_SCAT_COLNAME_0046 "Propensity"
//	#define STRMSG_S_SCAT_COLNAME_0047 "social position"
//	#define STRMSG_S_SCAT_COLNAME_0048 "Whole connection time"
//	#define STRMSG_S_SCAT_COLNAME_0049 "Generated time"
//	#define STRMSG_S_SCAT_COLNAME_0050 "Final log in time"
//	#define STRMSG_S_SCAT_COLNAME_0051 "Type"
//	#define STRMSG_S_SCAT_COLNAME_0052 "Whole"
	#define STRMSG_S_SCAT_COLNAME_0053 "Automatic type(1-1type)"
	#define STRMSG_S_SCAT_COLNAME_0054 "Vulcan type(1-1type)"	
	#define STRMSG_S_SCAT_COLNAME_0055 "Dualist type(1-1type)" // 2005-08-01 by hblee : Grenade -> changed to dualist.
	#define STRMSG_S_SCAT_COLNAME_0056 "Cannon type(1-1type)"
	#define STRMSG_S_SCAT_COLNAME_0057 "Rifle type(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0058 "Gatling type(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0059 "Launcher type(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0060 "Mass drive type(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0061 "Rocket type(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0062 "Missile type(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0063 "Bundle type(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0064 "Mine type(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0065 "kalkan type(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0066 "Dummy type(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0067 "Pixer type(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0068 "Decoy type(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0069 "savunma type"
	#define STRMSG_S_SCAT_COLNAME_0070 "Support ekipman type"
	#define STRMSG_S_SCAT_COLNAME_0071 "enerji type"
	#define STRMSG_S_SCAT_COLNAME_0072 "Metal type"
	#define STRMSG_S_SCAT_COLNAME_0073 "kart type"
	#define STRMSG_S_SCAT_COLNAME_0074 "büyüle type"
	#define STRMSG_S_SCAT_COLNAME_0075 "Tank type"
	#define STRMSG_S_SCAT_COLNAME_0076 "Bullet type"
	#define STRMSG_S_SCAT_COLNAME_0077 "içiçinde görev"
	#define STRMSG_S_SCAT_COLNAME_0078 "Radar type"
	#define STRMSG_S_SCAT_COLNAME_0079 "Computer type"
	#define STRMSG_S_SCAT_COLNAME_0080 "şans denemesi kart type"
	#define STRMSG_S_SCAT_COLNAME_0081 "büyüle Destruction Prevention type"		// 2005-08-02 by cmkwon
	#define STRMSG_S_SCAT_COLNAME_0082 "Blaster type"				// 2005-08-02 by cmkwon
	#define STRMSG_S_SCAT_COLNAME_0083 "Rail gun type"				// 2005-08-02 by cmkwon
//	#define STRMSG_S_SCAT_COLNAME_0081 "Whole item"
//	#define STRMSG_S_SCAT_COLNAME_0082 "Whole server"
//	#define STRMSG_S_SCAT_COLNAME_0083 "Server name"
//	#define STRMSG_S_SCAT_COLNAME_0084 "Server type"
//	#define STRMSG_S_SCAT_COLNAME_0085 "Server IP, Port"
//	#define STRMSG_S_SCAT_COLNAME_0086 "Present number of users"
//	#define STRMSG_S_SCAT_COLNAME_0087 "Server condition"
//	#define STRMSG_S_SCAT_COLNAME_0088 "Group server"
//	#define STRMSG_S_SCAT_COLNAME_0089 "Field server"
//	#define STRMSG_S_SCAT_COLNAME_0090 "Unknown"
//	#define STRMSG_S_SCAT_COLNAME_0091 "Not executed"
//	#define STRMSG_S_SCAT_COLNAME_0092 "Normal"
//	#define STRMSG_S_SCAT_COLNAME_0093 "Abnormal"
	#define STRMSG_S_SCAT_COLNAME_0094 "Administrator"

	#define STRMSG_S_SCADMINTOOL_050512_0000	"CAST(l.CurrentCount AS VARCHAR(10)) + '개, Param1:' + CAST(l.Param1 AS VARCHAR(10))"
// 3_end
///////////////////////////////////////////////////////////////////////////////
	
	
///////////////////////////////////////////////////////////////////////////////
// 4
	// 4-1 AtumMonitor - STRMSG
//	#define STRMSG_S_SCMONITOR_0000 "Command list\r\n"
//	#define STRMSG_S_SCMONITOR_0001 "----- List of backup account ---------------------------------------\r\n"
//	#define STRMSG_S_SCMONITOR_0002 "  Account: \'%s\', Original password: \'%s\', Temporary password: \'%s\'\r\n"
//	#define STRMSG_S_SCMONITOR_0003 "  Account: \'%s\' \r\n"
//	#define STRMSG_S_SCMONITOR_0004 "Please choose the folder where Versions for update are located"
//	#define STRMSG_S_SCMONITOR_0005 "\r\nMaking New Zip File From %s To %s...\r\n"
//	#define STRMSG_S_SCMONITOR_0006 "Rename Server Group"
//	#define STRMSG_S_SCMONITOR_0007 "File has been succesfully created.\r\n\r\nDB information: %s(%d), %s"
//	#define STRMSG_S_SCMONITOR_0008 "%04d(%2d -  active) %3d/%3d"
//	#define STRMSG_S_SCMONITOR_0009 "%04d(%2d -inactive) %3d/%3d"
//	#define STRMSG_S_SCMONITOR_0010 "Servers data has been succesfully reloaded."
//	#define STRMSG_S_SCMONITOR_0011 "Service condition has been succesfully reflected."
//	#define STRMSG_S_SCMONITOR_0012 "%04d(%2d -  active)"
//	#define STRMSG_S_SCMONITOR_0013 "%04d(%2d -inactive)"
//	#define STRMSG_S_SCMONITOR_0014 "Version Info List Reload DONE!"
//	#define STRMSG_S_SCMONITOR_0015 "Blocked Account List Reload DONE!"
//	#define STRMSG_S_SCMONITOR_0016 "Free server service has been stopped."
//	#define STRMSG_S_SCMONITOR_0017 "Free server service started."
//	#define STRMSG_S_SCMONITOR_0018 "Field server is not executed"
//	#define STRMSG_S_SCMONITOR_0019 "Do you really want to close Field Server?"
//	#define STRMSG_S_SCMONITOR_0020 "Update version list information(Maximum 1492 Bytes)\r\n\r\n    Number of version list[%3d], Data capacity[%4dBytes]"
//	#define STRMSG_S_SCMONITOR_0021 "Do you really want to close Pre Server?"
//	#define STRMSG_S_SCMONITOR_0022 "Do you really want to close IM Server?"
//	#define STRMSG_S_SCMONITOR_0023 "Do you really want to close NPC Server?"
//	#define STRMSG_S_SCMONITOR_0024 "%Yyear %mmonth %dday %Hhour %Mminute %Ssecond"
//	#define STRMSG_S_SCMONITOR_0025 "No event(%d)"
//	#define STRMSG_S_SCMONITOR_0026 "Open beta attendance event(%d)"
//	#define STRMSG_S_SCMONITOR_0027 "Do not know event(%d)"
//	#define STRMSG_S_SCMONITOR_0028 "Set up time for next occupying battle"
//	#define STRMSG_S_SCMONITOR_0029 "Standard time for next occupying battle"
//	#define STRMSG_S_SCMONITOR_0030 "Occupying brigade"

	// 4-2 AtumMonitor - STRERR
//	#define STRERR_S_SCMONITOR_0000 "  ==> Command succesful.\r\n"
//	#define STRERR_S_SCMONITOR_0001 "  ==> Command failed.\r\n"
//	#define STRERR_S_SCMONITOR_0002 "Cannot connect to the DB."
//	#define STRERR_S_SCMONITOR_0003 "Corresponding Version do not exist"
//	#define STRERR_S_SCMONITOR_0004 "Please enter name of the folder that you want to compress"
//	#define STRERR_S_SCMONITOR_0005 "Please enter name of the folder that you want to output"
//	#define STRERR_S_SCMONITOR_0006 "Please enter start version"
//	#define STRERR_S_SCMONITOR_0007 "Please enter last version"
//	#define STRERR_S_SCMONITOR_0008 "Please choose the folder that you are going to output Zip file for update"
//	#define STRERR_S_SCMONITOR_0009 "Cannot connect file"
//	#define STRERR_S_SCMONITOR_0010 "Please choose the server!"
//	#define STRERR_S_SCMONITOR_0011 "Cannot connect to the DB"
//	#define STRERR_S_SCMONITOR_0012 "[Error]Unable to process Message Type: %s(%#04x) in CLeftView::OnSocketNotify()\n"
//	#define STRERR_S_SCMONITOR_0013 "There is too many update version list.(Version list number[%3d], Data capacity[%4dBytes])\r\n\r\n    You must arrange version list."
//	#define STRERR_S_SCMONITOR_0014 "Eliminated function.\r\nPlease use management tool."
//	#define STRERR_S_SCMONITOR_0015 "This is not a city occupying map"
//	#define STRERR_S_SCMONITOR_0016 "Cannot make EDIT control."
//	#define STRERR_S_SCMONITOR_0017 "You have already registered existing file."

// 4_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 5 - FieldServer
	// 5-1 Field<->Log
	#define STRMSG_S_F2LOGCONNECT_0000 "[hata] WndProc(), -ebilir't connect -e LogServer[%15s:%4d] Reconnect\r\n"
	#define STRMSG_S_F2LOGCONNECT_0001 "Logged into Log sunucu.\n"
	#define STRMSG_S_F2LOGCONNECT_0002 "bağlantı -e Log sunucu[%15s:%4d]has been lost. Trying reconnection.\r\n"

	// 5-2 Field<->Pre
	#define STRMSG_S_F2PRECONNECT_0000 "[hata] WndProc(), -ebilir't connect -e PreServer[%15s:%4d] Reconnect\r\n"
	#define STRMSG_S_F2PRECONNECT_0001 "Logged into Pre sunucu.\n"
	#define STRMSG_S_F2PRECONNECT_0002 "T_ERROR %s(%#04X) alındı -den %s[%s]\r\n"
	#define STRMSG_S_F2PRECONNECT_0003 "bilinmeyen hata@WM_PRE_PACKET_NOTIFY: %s(%#04x)\n"
	#define STRMSG_S_F2PRECONNECT_0004 "bağlantı -e Pre sunucu[%15s:%4d]has been lost. Trying reconnection.\r\n"

	// 5-3 Field<->IM
	#define STRMSG_S_F2IMCONNECT_0000 "[hata] WndProc(), -ebilir't connect -e IMServer[%15s:%4d] Reconnect\r\n"
	#define STRMSG_S_F2IMCONNECT_0001 "Logged into IM sunucu.\n"
	#define STRMSG_S_F2IMCONNECT_0002 "bağlantı -e IM sunucu[%15s:%4d]has been lost. Trying reconnection.\r\n"
	#define STRMSG_S_F2IMCONNECT_0003 "T_ERROR %s(%#04X) alındı -den %s[%s]\r\n"
	#define STRMSG_S_F2IMCONNECT_0004 "bilinmeyen hata@WM_IM_PACKET_NOTIFY: %s(%#04x)\n"

	// 5-3 Field - DB
	#define STRMSG_S_F2DBQUERY_0000 "yok such DB sorgu içinde Field sunucu Queries! %d\n"
	#define STRMSG_S_F2DBQUERY_0001 "ilgili eşya does mevcut değil."
	#define STRMSG_S_F2DBQUERY_0002 "'%s'has applied içiçinde attendance, so promised eşya"
	#define STRMSG_S_F2DBQUERY_0003 "given. Press F5 -e check sizin envanter"
	#define STRMSG_S_F2DBQUERY_0004 "beceri %s(%d)has been eklendi"
	#define STRMSG_S_F2DBQUERY_0005 "ilgili eşya does mevcut değil."
	#define STRMSG_S_F2DBQUERY_0006 "başarısız oldu: satın alma eşya."

	// 5-4 Field - CityWar
	#define STRMSG_S_F2CITYWAR_0000 "şehir occupying savaş start: %d(%10s) occGuildName(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0001 "Participating tugay: GuildUID(%4d) GuildName(%10s) GuildMaster(%d)\r\n"
	#define STRMSG_S_F2CITYWAR_0002 "şehir occupying savaş canavar explosion: %d(%10s) occGuildName(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0003 "hasar sum total ==> GuildName(%10s) SumOfDamage(%8.2f)\r\n"
	#define STRMSG_S_F2CITYWAR_0004 "şehir occupying savaş: %d(%10s) CityMapIndex(%d) QuestIndex(%d) OccGuildID(%d) OccGuildName(%s) OccGuildMasterUID(%d) 점령전시간(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0005 "[hata] SetCityWarState_ DBError, MapIndex(%d)\r\n"
	#define STRMSG_S_F2CITYWAR_0006 "After %ddakika, \"%s\" şehir occupying savaş başlayacak."
	#define STRMSG_S_F2CITYWAR_0007 "After %ddakika, \"%s\" şehir occupying savaş olacak finished."
	#define STRMSG_S_F2CITYWAR_0008 "canavar çağrıldı içiçinde şehir occupying savaş(%s): NPC occupying"
	#define STRMSG_S_F2CITYWAR_0009 "canavar çağrıldı içiçinde şehir occupying savaş(%s): %s tugay occupying"
	#define STRMSG_S_F2CITYWAR_0010 "\"NPC\" occupying \"%s\" presently."
	#define STRMSG_S_F2CITYWAR_0011 "\"%s\"bridgade occupying \"%s\" presently."

	// 5-4 Field - Quest
	#define STRMSG_S_F2QUEST_0000 "başarısız oldu: yükle görev"
	#define STRMSG_S_F2QUEST_0001 "görev has değil been yüklendi.\r\n"
//	#define STRMSG_S_F2QUEST_0002 "퀘스트 \'%30s\' 번호 %d -> OK\r\n"

	// 5-4 Field - config
	#define STRMSG_S_F2CONFIG_0000 "sunucu içiçinde test has been set! \r\n\r\nLoadFieldServerDataDebug() needs -e be eliminated!"
	#define STRMSG_S_F2NOTIFY_0000 "splash %d: %d-e %5.2f(%2.1f%%)"
	#define STRMSG_S_F2NOTIFY_0001 "canavar splash %d: %s-e %5.2f"
	#define STRMSG_S_F2NOTIFY_0002 "1st type"
	#define STRMSG_S_F2NOTIFY_0003 "2nd type"
	#define STRMSG_S_F2NOTIFY_0004 "Mon1(%s)"
	#define STRMSG_S_F2NOTIFY_0005 "Mon2(%s)"
	#define STRMSG_S_F2NOTIFY_0006 "Wrong silah type! Please make inquiry -e yönetici!"
	#define STRMSG_S_F2NOTIFY_0007 "1-1type: %4.1f vs %4.1f -> saldırı olasılık reduced tarafından %2.2f%%"
	#define STRMSG_S_F2NOTIFY_0008 "%s->%s fail, olasılık(%d>%5.2f)"
	#define STRMSG_S_F2NOTIFY_0009 "%s->%s fail, olasılık(%d>%5.2f) -%5.2f"
	#define STRMSG_S_F2NOTIFY_0010 "%s->%s fail, olasılık(%d>%5.2f)"
	#define STRMSG_S_F2NOTIFY_0011 "1-2type: %4.1f vs %4.1f -> hasar reduced tarafından %2.2f%%(%4.1f->%4.1f)"
	#define STRMSG_S_F2NOTIFY_0012 "%s->%s, gives %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0013 "%s->%s, receives %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0014 "%s->%s(%d, HP:%5.2f), gives %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0015 "%s->%s, receives %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0016 "Dummy başarısız: olasılık yetersiz > %d"
	#define STRMSG_S_F2NOTIFY_0017 "kalan dummy[%#08x]: %5.2f(%5.2f-%5.2f)"
	#define STRMSG_S_F2NOTIFY_0018 "Bullet bilgi does mevcut değil. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0019 "bilgi about bullets calibre does mevcut değil. %s %d"
	#define STRMSG_S_F2NOTIFY_0020 "bu bullet's bilgi. %s %d"
	#define STRMSG_S_F2NOTIFY_0021 "ışınlan değil possible while etkinlik devam ediyor"
	#define STRMSG_S_F2NOTIFY_0022 "ışınlan değil possible when siz oluyor ölü."
	#define STRMSG_S_F2NOTIFY_0023 "ışınlan değil possible if siz oluyor içinde filo savaş"
	#define STRMSG_S_F2NOTIFY_0024 "harita production hata! Please make inquiry -e yönetici!"
	#define STRMSG_S_F2NOTIFY_0025 "harita production hata! Please make inquiry -e yönetici! %d, %d sayı ışınlan hedef index does mevcut değil!\r\n"
	#define STRMSG_S_F2NOTIFY_0026 "ışınlan değil possible if filo savaş devam ediyor"
	#define STRMSG_S_F2NOTIFY_0027 "ışınlan(%04d) treatment değil possible Process_FC_CHARACTER_DEAD_GAMESTART(), %s\r\n"
	#define STRMSG_S_F2NOTIFY_0028 "1 -> karakter %10s,receives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0029 "1 -> karakter %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0030 "1 -> karakter %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0031 "1 -> karakter %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0032 "2 -> karakter %10s,receives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0033 "2 -> karakter %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0034 "2 -> canavar %3d,gives hasar %5.2f(%d)"
	#define STRMSG_S_F2NOTIFY_0035 "2 -> karakter %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0036 "2 -> karakter %10s,gives dummy hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0037 "2 -> canavar %3d,receives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0038 "MINE -> karakter %10s, gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0039 "MINE -> karakter %10s,gives dummy hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0040 "MINE -> canavar %10s,gives hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0041 "Stat initialization has been successful."
	#define STRMSG_S_F2NOTIFY_0042 "yapılamıyor kullan bu when siz oluyor ölü"
	#define STRMSG_S_F2NOTIFY_0043 "ENCHANT_INFO does mevcut değil"
	#define STRMSG_S_F2NOTIFY_0044 "büyüle successful."
	#define STRMSG_S_F2NOTIFY_0045 "büyüle başarısız."
	#define STRMSG_S_F2NOTIFY_0046 "Does değil belong -e tugay."
	#define STRMSG_S_F2NOTIFY_0047 "zaten içinde standby state içiçinde request."
	#define STRMSG_S_F2NOTIFY_0048 "lütfen daha sonra tekrar deneyin."
	#define STRMSG_S_F2NOTIFY_0049 "siz veya diğer person tugay leader."
	#define STRMSG_S_F2NOTIFY_0050 "zaten içinde tugay savaş."
	#define STRMSG_S_F2NOTIFY_0051 "Both tugay leaders do mevcut değil içinde aynı harita."
	#define STRMSG_S_F2NOTIFY_0052 "tüm filo üyeler oluyor değil içinde aynı harita"
	#define STRMSG_S_F2NOTIFY_0053 "tüm filo üyeler oluyor değil içinde aynı harita"
	#define STRMSG_S_F2NOTIFY_0054 "siz do değil belong -e tugay."
	#define STRMSG_S_F2NOTIFY_0055 "receiving applicant different."
	#define STRMSG_S_F2NOTIFY_0056 "siz veya diğer person değil tugay leader."
	#define STRMSG_S_F2NOTIFY_0057 "Two tugay leaders do mevcut değil içinde aynı harita."
	#define STRMSG_S_F2NOTIFY_0058 "siz do değil belong -e tugay."
	#define STRMSG_S_F2NOTIFY_0059 "receiving applicant different."
	#define STRMSG_S_F2NOTIFY_0060 "siz veya diğer person değil tugay leader."
	#define STRMSG_S_F2NOTIFY_0061 "Successful içinde şehir occupying savaş savunma"
	#define STRMSG_S_F2NOTIFY_0062 "misyon setup hata. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0063 "ilgili eşya(%s) cannot be fitted bu location"
	#define STRMSG_S_F2NOTIFY_0064 "motor cannot be vacated."
	#define STRMSG_S_F2NOTIFY_0065 "eşya hareket et: (%I64d, %d) -> (%I64d, %d)"
	#define STRMSG_S_F2NOTIFY_0066 "Wrong eşya movement: (%I64d, %d) -> (%I64d, %d)"
	#define STRMSG_S_F2NOTIFY_0067 "etkinlik(%d) yapılamıyor handle Process_FC_EVENT_REQUEST_WARP(), %s\r\n"
	#define STRMSG_S_F2NOTIFY_0068 "harita etkinlik bilgi abnormal!!! Please make inquiry -e yönetici!!!"
	#define STRMSG_S_F2NOTIFY_0069 "ilgili ışınlan hedef does mevcut değil"
	#define STRMSG_S_F2NOTIFY_0070 "eşya satın alma hata. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0071 "beceri seviye şu siz want -e satın alma lower veya sizin current seviye."
	#define STRMSG_S_F2NOTIFY_0072 "eşya hata. eşya needs beceri satın alma."
	#define STRMSG_S_F2NOTIFY_0073 "eşya selling hata. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0074 "eşya satın alma hata. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0075 "\'kredi eşya\'has been purchased."
	#define STRMSG_S_F2NOTIFY_0076 "satın alma list: \'%s(%dpieces)\'"
	#define STRMSG_S_F2NOTIFY_0077 "zaten joined grup."
	#define STRMSG_S_F2NOTIFY_0078 "yapılamıyor join if siz oluyor grup leader"
	#define STRMSG_S_F2NOTIFY_0079 "Cannot join if filo savaş under progress."
	#define STRMSG_S_F2NOTIFY_0080 "Bringing up tüm filo personnel bilgi değil supported!"
	#define STRMSG_S_F2NOTIFY_0081 "harita etkinlik bilgi abnormal!!! Please make inquiry -e yönetici!!!"
	#define STRMSG_S_F2NOTIFY_0082 "bu hesap şu cannot make transaction"
	#define STRMSG_S_F2NOTIFY_0083 "%s's kapasite has exceeded."
	#define STRMSG_S_F2NOTIFY_0084 "Possible movement coordination: (5, 5) -> (%d, %d)"
	#define STRMSG_S_F2NOTIFY_0085 "kullanıcı:"
	#define STRMSG_S_F2NOTIFY_0086 "maksimum 20 people -ebilir be seen."
	#define STRMSG_S_F2NOTIFY_0087 "ilgili kullanıcı(%s)do mevcut değil"
	#define STRMSG_S_F2NOTIFY_0088 "Does değil belong -e grup"
	#define STRMSG_S_F2NOTIFY_0089 "hediye zaman: %d:%d, Artum zaman: %d:%d"
	#define STRMSG_S_F2NOTIFY_0090 "Changed zaman: %d:%d, Artum zaman: %d:%d"
	#define STRMSG_S_F2NOTIFY_0091 "değil bağlandı -e NPC sunucu"
	#define STRMSG_S_F2NOTIFY_0092 "ilgili eşya(%d)do mevcut değil"
	#define STRMSG_S_F2NOTIFY_0093 "Limited -e 10 pieces if it değil stackable eşya"
	#define STRMSG_S_F2NOTIFY_0094 "harita \'%s\' 's whole sayı bağlandı person: %dpeople"
	#define STRMSG_S_F2NOTIFY_0095 "harita %s %s simultaneous bağlantı: %dpeople - '%s'(*)"
	#define STRMSG_S_F2NOTIFY_0096 "harita %s %s simultaneous bağlantı: %dpeople - '%s'"
	#define STRMSG_S_F2NOTIFY_0097 "hediye harita kanal: %s, %d(%d)"
	#define STRMSG_S_F2NOTIFY_0098 "bilgi bullets do mevcut değil. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0099 "bilgi about bullets calibre does mevcut değil. %s %d"
	#define STRMSG_S_F2NOTIFY_0100 "bilgi about bullets does mevcut değil. Please make inquiry -e yönetici."
	#define STRMSG_S_F2NOTIFY_0101 "bilgi about bullets calibre does mevcut değil. %s %d"
	#define STRMSG_S_F2NOTIFY_0102 "ilgili kullanıcı(%s)does mevcut değil"
	#define STRMSG_S_F2NOTIFY_0103 "ilgili kullanıcı(%s) ölü"
	#define STRMSG_S_F2NOTIFY_0104 "ilgili users(%s)do mevcut değil"
	#define STRMSG_S_F2NOTIFY_0105 "Set as standart hesap"
	#define STRMSG_S_F2NOTIFY_0106 "standart hesap has been iptal edildi"
	#define STRMSG_S_F2NOTIFY_0107 "Invincibility has been turned üzerinde."
	#define STRMSG_S_F2NOTIFY_0108 "Invincibility has been turned off."
	#define STRMSG_S_F2NOTIFY_0109 "silah hasar olacak modified tarafından %5.0f%%"
	#define STRMSG_S_F2NOTIFY_0110 "olacak initialized when reloading eşya"
	#define STRMSG_S_F2NOTIFY_0111 "olacak initialized when reloading eşya"
	#define STRMSG_S_F2NOTIFY_0112 "ilgili kullanıcı(%s)does mevcut değil"
	#define STRMSG_S_F2NOTIFY_0113 "Invisibility has been deactivated."
	#define STRMSG_S_F2NOTIFY_0114 "Invisibility has been activated."
	#define STRMSG_S_F2NOTIFY_0115 "%s etkinlik değil under progress"
	#define STRMSG_S_F2NOTIFY_0116 "%s etkinlik has başlatıldı(magnification:%4.2f, etkinlik zaman:%3ddakika)"
	#define STRMSG_S_F2NOTIFY_0117 "Set as standart premium hesap"
	#define STRMSG_S_F2NOTIFY_0118 "başarısız oldu: set as premium hesap"
	#define STRMSG_S_F2NOTIFY_0119 "Set as süper premium hesap"
	#define STRMSG_S_F2NOTIFY_0120 "bu değil harita içiçinde şehir occupying savaş"
	#define STRMSG_S_F2NOTIFY_0121 "şehir occupying savaş cannot be başlatıldı"
	#define STRMSG_S_F2NOTIFY_0122 "şehir occupying savaş cannot be finished"
	#define STRMSG_S_F2NOTIFY_0123 "gizlilik mode has been initialized"
	#define STRMSG_S_F2NOTIFY_0124 "içinde gizlilik state"
	#define STRMSG_S_F2NOTIFY_0125 "harita değil validated."
	#define STRMSG_S_F2NOTIFY_0126 "mutlu saat etkinlik set [progress zaman:%4ddakika)]"
	#define STRMSG_S_F2NOTIFY_0127 "mutlu saat etkinlik finished"
	#define STRMSG_S_F2NOTIFY_0128 "1 -> -den canavar %3d,alındı hasar %5.2f"
	#define STRMSG_S_F2NOTIFY_0129 "1type -> -den canavar %3d,alındı hasar %5.2f(dummy)"
	#define STRMSG_S_F2NOTIFY_0130 "giriş yapıldı ile %s yetki"
	#define STRMSG_S_F2NOTIFY_0131 "Do değil process completing routine %s: CS(%d), DBStore(%d)\r\n"
	#define STRMSG_S_F2NOTIFY_0132 "hata@CharacterGameEndRoutine(): başarısız oldu: eliminate grup personnel! %s\r\n"
// 2005-11-24 by cmkwon, 
//	#define STRMSG_S_F2NOTIFY_0133 "Prefix \'%s\' 성공: %d <= %d <= %d\r\n"
//	#define STRMSG_S_F2NOTIFY_0134 "Suffix \'%s\' 성공: %d <= %d <= %d\r\n"
	#define STRMSG_S_F2NOTIFY_0135 "%s: durduruldu!"
	#define STRMSG_S_F2NOTIFY_0136 "FATAL hata: Please make inquiry -e yönetici! mağaza variable allotment hata!"
	#define STRMSG_S_F2NOTIFY_0137 "%s silindi."
	#define STRMSG_S_F2NOTIFY_0138 "kanal şu siz oluyor presently deactivated so monsters ve diğer functions oluyor değil mevcut."
	#define STRMSG_S_F2NOTIFY_0139 "durduruldu. lütfen kullanın başka kanal."
	#define STRMSG_S_F2NOTIFY_0140 "ışınlan Obj.[%s,%2dpieces]: %04d[%1s%4d]"
	#define STRMSG_S_F2NOTIFY_0141 "Timer movement %s\r\n"
	#define STRMSG_S_F2NOTIFY_0142 "HP auto recovery durduruldu"
	#define STRMSG_S_F2NOTIFY_0143 "HP auto recovery has durduruldu as bu değil possible location içiçinde landing"
	#define STRMSG_S_F2NOTIFY_0144 "HP 5.2f recovery içiçinde emergency"
	#define STRMSG_S_F2NOTIFY_0145 "Gradual HP UP durduruldu(kalan zaman: %d)"
	#define STRMSG_S_F2NOTIFY_0146 "Gradual DP UP durduruldu(kalan zaman: %d)"
	#define STRMSG_S_F2NOTIFY_0147 "Gradual EP UP durduruldu(kalan zaman: %d)"
	#define STRMSG_S_F2NOTIFY_0148 "%s etkinlik has been completed."
	#define STRMSG_S_F2NOTIFY_0149 "%s etkinlik under progress (magnification %4.2f, kalan:%3ddakika)"
	#define STRMSG_S_F2NOTIFY_0150 "Command has değil been exercised"


	// 5-5 Field - NOTIFY Error
	#define STRERR_S_F2NOTIFY_0000 "deneyim point division hata(%s, %s(%d)): fTotalDamage(%d) < 0.0f veya Empty Vector: %d, Distance(%5.1f)\n"
	#define STRERR_S_F2NOTIFY_0001 "değil geçerli Game Start mesaj hata ClientState[%d]\r\n"
	#define STRERR_S_F2NOTIFY_0002 "değil geçerli Game Start mesaj hata ClientState[%d]\r\n"
	#define STRERR_S_F2NOTIFY_0003 "ışınlan(%04d) treatment impossible ProcessQuestResult(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0004 "harita etkinlik bilgi abnormal!!! Please make inquiry -e yönetici!!! Current(%s, %s, %04d), hedef(%04d, %d)\r\n"
	#define STRERR_S_F2NOTIFY_0005 "etkinlik(%d) treatment impossible T_FC_PARTY_REQUEST_PARTY_WARP(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0006 "harita etkinlik bilgi abnormal!!! Please make inquiry -e yönetici!!! Current(%s, %s, %04d), hedef(%04d, %d)\r\n"
	#define STRERR_S_F2NOTIFY_0007 "ışınlan treatment impossible T_FC_PARTY_REQUEST_PARTY_WARP(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0008 "etkinlik(%d) treatment impossible(grup leader) Process_FC_PARTY_REQUEST_PARTY_WARP_WITH_MAP_NAME(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0009 "ışınlan(%04d) treatment impossible Process_FC_PARTY_REQUEST_PARTY_WARP_WITH_MAP_NAME(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0010 "etkinlik(%d) treatment impossible Process_FC_EVENT_REQUEST_WARP(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0011 "ışınlan treatment impossible T_FC_PARTY_REQUEST_PARTY_WARP(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0012 "grup ışınlan başarısız: %s -> distance: %5.2f, bodycon: %d, %d"
	#define STRERR_S_F2NOTIFY_0013 "ışınlan(%04d) treatment impossible Process_FC_CHARACTER_DEAD_GAMESTART(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0014 "%s -> click overlapped OK button!!!\r\n"
	#define STRERR_S_F2NOTIFY_0015 "görev has değil been yüklendi.\r\n"
	#define STRERR_S_F2NOTIFY_0016 "ışınlan(%s) treatment impossible HandleAdminCommands(), /hareket et, %s\r\n"
	#define STRERR_S_F2NOTIFY_0017 "ışınlan(%s) treatment impossible HandleAdminCommands(), /send, %s\r\n"
	#define STRERR_S_F2NOTIFY_0018 "FATAL hata: bu mesaj should değil be sent -e field sunucu şu üyeler do değil belong -e. check it out\r\n"
	#define STRERR_S_F2NOTIFY_0019 "ışınlan(%04d) treatment impossible T_FI_ADMIN_CALL_CHARACTER, %s\r\n"
	#define STRERR_S_F2NOTIFY_0020 "ışınlan(%s) treatment impossible T_FI_ADMIN_MOVETO_CHARACTER, %s\r\n"

	// 5-6 Field - Event
	#define STRMSG_S_F2EVENTTYPE_0000 "deneyim point"
	#define STRMSG_S_F2EVENTTYPE_0001 "SPI"
	#define STRMSG_S_F2EVENTTYPE_0002 "Restoration deneyim point"
	#define STRMSG_S_F2EVENTTYPE_0003 "eşya drop"
	#define STRMSG_S_F2EVENTTYPE_0004 "nadir eşya drop"
	#define STRMSG_S_F2EVENTTYPE_0005 "savaş puanı etkinlik"
// 5_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 6 - IMServer
	// 6-1 IM<->Pre
	#define STRMSG_S_I2PRECONNECT_0000 "Logged into Pre sunucu.\n"
	#define STRMSG_S_I2PRECONNECT_0001 "bağlantı -e Pre sunucu[%15s:%4d]has been lost. Attempting reconnection.\r\n"

	// 6-2 IM Notify
	#define STRMSG_S_I2NOTIFY_0000 "\'%s\' zaten exists"
	#define STRMSG_S_I2NOTIFY_0001 "\'%s\' zaten içinde tugay."
	#define STRMSG_S_I2NOTIFY_0002 "\'%s\' zaten isim existing tugay"
	#define STRMSG_S_I2NOTIFY_0003 "tugay yükleniyor başarısız - Please make inquiry -e yönetici!"
	#define STRMSG_S_I2NOTIFY_0004 "arkadaş '%s' has giriş yapıldı"
	#define STRMSG_S_I2NOTIFY_0005 "Checking previous filo"
	#define STRMSG_S_I2NOTIFY_0006 "Previous filo does mevcut değil"
	#define STRMSG_S_I2NOTIFY_0007 "Rejoined filo"
	#define STRMSG_S_I2NOTIFY_0008 "siz oluyor şu anda içinde filo"
	#define STRMSG_S_I2NOTIFY_0009 "Fatal hata: Fatal grup hata! T_IC_PARTY_GET_MEMBER"
	#define STRMSG_S_I2NOTIFY_0010 "State filo personnel geçersiz"
	#define STRMSG_S_I2NOTIFY_0011 "filo personnel have zaten joined tugay"
	#define STRMSG_S_I2NOTIFY_0012 "şu person has zaten joined tugay"
	#define STRMSG_S_I2NOTIFY_0013 "siz cannot invite yourself"
	#define STRMSG_S_I2NOTIFY_0014 "siz oluyor içinde state where joining brigades değil allowed"
	#define STRMSG_S_I2NOTIFY_0015 "siz have exceeded sayı tugay personnel şu -ebilir join"
	#define STRMSG_S_I2NOTIFY_0016 "siz oluyor içinde state where joining brigades değil allowed"
	#define STRMSG_S_I2NOTIFY_0017 "tugay leader cannot withdraw -den tugay"
	#define STRMSG_S_I2NOTIFY_0018 "Cannot withdraw -den tugay while siz oluyor içinde tugay savaş"
	#define STRMSG_S_I2NOTIFY_0019 "Cannot expel tugay personnel while içinde tugay savaş"
	#define STRMSG_S_I2NOTIFY_0020 "tugay leader cannot be expelled"
	#define STRMSG_S_I2NOTIFY_0021 "Cannot disperse tugay while siz oluyor içinde tugay savaş"
	#define STRMSG_S_I2NOTIFY_0022 "Cannot değiştir -e aynı isim"
	#define STRMSG_S_I2NOTIFY_0023 "siz oluyor içinde state where tugay isim değiştirilemez"
	#define STRMSG_S_I2NOTIFY_0024 "siz oluyor içinde state where tugay mark değiştirilemez"
	#define STRMSG_S_I2NOTIFY_0025 "siz oluyor içinde state where rütbe değiştirilemez"
	#define STRMSG_S_I2NOTIFY_0026 "rütbe has overlapped"
	#define STRMSG_S_I2NOTIFY_0027 "rütbe değiştir -e regiment leader değil possible."
	#define STRMSG_S_I2NOTIFY_0028 "değiştir içinde regiment leaders rütbe değil possible."
	#define STRMSG_S_I2NOTIFY_0029 "sayı whole users: %dpersons (çıktı up -e %dpeople)"
	#define STRMSG_S_I2NOTIFY_0030 "eklendi -e administrators mesaj list"
	#define STRMSG_S_I2NOTIFY_0031 "silindi -den administrators mesaj list"
	#define STRMSG_S_I2NOTIFY_0032 "sunucu IP: %s"
	#define STRMSG_S_I2NOTIFY_0033 "sunucu group \'%s\' total sayı people logged üzerinde: %dpeople"
	#define STRMSG_S_I2NOTIFY_0034 "Do siz really want -e kapat sunucu(%s)? sayı: %d"
	#define STRMSG_S_I2NOTIFY_0035 "\'%s\' değil playing game"
	#define STRMSG_S_I2NOTIFY_0036 "sayı whole users: %dpersons (çıktı up -e %dpeople)"
	#define STRMSG_S_I2NOTIFY_0037 "/send %s %s"
	#define STRMSG_S_I2NOTIFY_0038 "ilgili regiment does mevcut değil."
	#define STRMSG_S_I2NOTIFY_0039 "fısıltı block has been devre dışı"
	#define STRMSG_S_I2NOTIFY_0040 "fısıltı has been blocked"
	#define STRMSG_S_I2NOTIFY_0041 "Did değil join tugay"
	#define STRMSG_S_I2NOTIFY_0042 "tugay(%d) değil mevcut"
	#define STRMSG_S_I2NOTIFY_0043 "ilgili hava durumu(%s)does mevcut değil"
	#define STRMSG_S_I2NOTIFY_0044 "Field sunucu geçersiz"
	#define STRMSG_S_I2NOTIFY_0045 "ilgili harita(%s) does mevcut değil"
	#define STRMSG_S_I2NOTIFY_0046 "siz cannot sohbet içiçinde %d!dakika!!"
	#define STRMSG_S_I2NOTIFY_0047 "sohbet block set: '%10s', %3ddakika"
	#define STRMSG_S_I2NOTIFY_0048 "sohbet block condition has been iptal edildi."
	#define STRMSG_S_I2NOTIFY_0049 "sohbet block iptal edildi: '%10s'"
	#define STRMSG_S_I2NOTIFY_0050 "%s(hesap: %s, harita: %d(%d), seviye: %d) PLAYING"
	#define STRMSG_S_I2NOTIFY_0051 "Cannot çağır yourself."
	#define STRMSG_S_I2NOTIFY_0052 "ilgili tugay does mevcut değil."

	#define STRMSG_S_IMSERVER_050607_0001	"ilgili harita does mevcut değil."
// 6_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 7 - NPCServer
	// 7-1 NPC<->Field
	#define STRMSG_S_N2FIELDCONNECT_0000 "Logged into field sunucu.\n"
	#define STRMSG_S_N2FIELDCONNECT_0001 "bağlantı -e field sunucu[%15s:%4d]has been lost. Attempting reconnection.\r\n"

	// 7-2 IM Notify
	#define STRMSG_S_N2NOTIFY_0000 "çarpışma check between canavar ve nesne does mevcut değil\r\n"
	#define STRMSG_S_N2NOTIFY_0001 "şehir occupying savaş canavar(%10s) çağrıldı\r\n\r\n"

	#define STRMSG_S_N2TESTMONNAME_0000 "Chul min ho"
// 7_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 8 - PreServer
	// 8-1 Pre Notify
	#define STRMSG_S_P2PRENOTIFY_0000 "giriş yapıldı ile %s hesap(%s). IP: %s\r\n"
	#define STRMSG_S_P2PRENOTIFY_0001 "başarılı"
	#define STRMSG_S_P2PRENOTIFY_0002 "Failure"
	#define STRMSG_S_P2PRENOTIFY_0003 "[hata] hata içinde adding hesap bilgi, AccountName(%s) privateIP(%15s)\n"


	#define STRMSG_SCAT_051115_0001		"Hello. bu ACE Online yönetici."
	#define STRMSG_SCAT_051115_0002		"We olacak performing our regular bakım içinde 10 dakika."
	#define STRMSG_SCAT_051115_0003		"Please hareket et -e safe area ve exit -den game."
	#define STRMSG_SCAT_051115_0004		"First, NPC sunucu olacak shut down."
	#define STRMSG_SCAT_051115_0005		"ACE Online regular bakım will begin."
	#define STRMSG_SCAT_051115_0006		"Please enjoy sizin gün ile ACE Online."
	#define STRMSG_SCAT_051115_0007		"There olacak sunucu checkup içinde 5 dakika." // 5분 후 서버 점검이 있을 예정입니다.
	#define STRMSG_SCAT_051115_0008		"sunucu olacak down içiçinde 60 dakika."	// 서버는 60분 동안 내려질 예정입니다


///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

	// 2006-05-09 by cmkwon
	#define STRMSG_060509_0000			"görünmez Mode: Users cannot see siz ama silahlar kullanılamaz."
	#define STRMSG_060509_0001			"yenilmez Status: siz will değil receive any hasar."
	#define STRMSG_060509_0002			"gizlilik Mode: Monsters will değil saldırı siz first."

	// 2006-05-26 by cmkwon
	#define	STRMSG_060526_0000			"request has been sent -e GM. One our GMs will contact siz as soon as possible."
	#define	STRMSG_060526_0001			"siz yapılamıyor automatically update.\r\n\r\nPlease download patch -den ana sayfa(%s) ve connect again.\r\n\r\n hata: %s"

	// 2006-08-24 by cmkwon
	#define STRMSG_060824_0000			"bu ID has değil been kaydoldu veya ID ve şifre do değil match."
	
	// 2006-09-27 by cmkwon
	#define STRMSG_060927_0000			"game sunucu şu anda offline içiçinde bakım. lütfen kontrol edin official ana sayfa (https://oldschoolrivals.com) içiçinde further bilgi."

	// 2006-10-11 by cmkwon
	#define STRERR_061011_0000			"Game istemci version değil geçerli.\r\n Please reinstall veya download patch dosya."

	// 2006-11-07 by cmkwon
	#define STRMSG_061107_0000			"siz öldürüldü tarafından %s."

	// 2006-11-07 by cmkwon
	#define STRMSG_070410_0000   	"Jamboree sunucu DB(atum2_db_20) initialization must be conducted after closing jamboree sunucu."
	#define STRMSG_070410_0001   	"Do siz really want -e initialize jamboree sunucu DB(atum2_db_20)- [Validation sayı:%d]"
	#define STRMSG_070410_0002   	"Jamboree sunucu DB(atum2_db_20) initialized."
	#define STRMSG_070410_0003   	"Jamboree sunucu DB(atum2_db_20) initialization başarısız!!"
	#define STRMSG_070410_0004   	"'%s' data duplication -e Jamboree sunucu DB(atum2_db_20) completed."
	#define STRMSG_070410_0005   	"'%s' data duplication -e Jamboree sunucu DB(atum2_db_20) başarısız - karakter do mevcut değil!!"
	#define STRMSG_070410_0006   	"%s' data duplication -e Jamboree sunucu DB(atum2_db_20) başarısız - ilgili hesap karakter exists!!"
	#define STRMSG_070410_0007   	"%s' data duplication -e Jamboree sunucu DB(atum2_db_20) başarısız - DB addition başarısız!!"
	#define STRMSG_070410_0008   	"%s' data duplication -e Jamboree sunucu DB(atum2_db_20) başarısız - bilinmeyen (%d)!!"

///////////////////////////////////////////////////////////////////////////////
// 2007-05-07 by cmkwon, 해상도 문자열 
	// 2007-07-24 by cmkwon, 런처에서 800*600 해상도 삭제 - 콤보박스 스트링 필요 없음
	//#define STRMSG_WINDOW_DEGREE_800x600_LOW			"800x600 (low)"
	//#define STRMSG_WINDOW_DEGREE_800x600_MEDIUM			"800x600 (medium)"
	//#define STRMSG_WINDOW_DEGREE_800x600_HIGH			"800x600 (high)"
#define STRMSG_WINDOW_DEGREE_1024x768_LOW			"1024x768 L"
#define STRMSG_WINDOW_DEGREE_1024x768_MEDIUM		"1024x768 M"
#define STRMSG_WINDOW_DEGREE_1024x768_HIGH			"1024x768 H"
#define STRMSG_WINDOW_DEGREE_W1280x800_LOW			"1280x800 L"
#define STRMSG_WINDOW_DEGREE_W1280x800_MEDIUM		"1280x800 M"
#define STRMSG_WINDOW_DEGREE_W1280x800_HIGH			"1280x800 H"
#define STRMSG_WINDOW_DEGREE_1280x960_LOW			"1280x960 L"
#define STRMSG_WINDOW_DEGREE_1280x960_MEDIUM		"1280x960 M"
#define STRMSG_WINDOW_DEGREE_1280x960_HIGH			"1280x960 H"
#define STRMSG_WINDOW_DEGREE_1280x1024_LOW			"1280x1024 L"
#define STRMSG_WINDOW_DEGREE_1280x1024_MEDIUM		"1280x1024 M"
#define STRMSG_WINDOW_DEGREE_1280x1024_HIGH			"1280x1024 H"
#define STRMSG_WINDOW_DEGREE_W1600x900_LOW			"1600x900 L"
#define STRMSG_WINDOW_DEGREE_W1600x900_MEDIUM		"1600x900 M"
#define STRMSG_WINDOW_DEGREE_W1600x900_HIGH			"1600x900 H"
#define STRMSG_WINDOW_DEGREE_1600x1200_LOW			"1600x1200 L"
#define STRMSG_WINDOW_DEGREE_1600x1200_MEDIUM		"1600x1200 M"
#define STRMSG_WINDOW_DEGREE_1600x1200_HIGH			"1600x1200 H"

// 2007-06-15 by dhjin, 관전 관련 스트링
#define STRMSG_070615_0000		"Cannot start as siz oluyor değil içinde gizlilik Mode."
#define STRMSG_070615_0001		"Cannot start watch."
#define STRMSG_070620_0000	"kullanıcı cannot start watch."

// 2007-06-26 by dhjin, 워포인트 이벤트 관련 추가
#define STRMSG_S_F2EVENTTYPE_0006		"savaş puanı"

// 2007-06-28 by cmkwon, 중국 방심취관련(게임 시간 알림 구현) - 스트링 추가
#define STRMSG_070628_0000				"siz have been playing game içiçinde %d saat(s)."
#define STRMSG_070628_0001				"siz have been playing game içiçinde %d saat(s). Please take necessary steps -e get some rest."
#define STRMSG_070628_0002				"siz have played too long. It becoming dangerous içiçinde sizin health. Please take care sizin own health ve kapat game. bu içiçinde sizin own benefit."
#define STRMSG_070628_0003				"Playing bu game any daha fazla olacak critical -e sizin health. Look after sizin own health tarafından closing game right şimdi. If değil, sizin health olacak influenced, ve sizin game revenue will reach 0%. sizin game revenue olacak back -e normal 5 saat after game has been kapalı."

///////////////////////////////////////////////////////////////////////////////
// 2007-07-11 by cmkwon, Arena block system materialization - added string
#define STRMSG_070711_0000    "\'%s\' değil prohibited içinde entering arena."
#define STRMSG_070711_0001 "\'%s\' prohibited içinde entering arena (zaman kalan: %d dakika)"
#define STRMSG_070711_0002 "siz oluyor forbidden -den entering arena içiçinde %d dakika!!"
#define STRMSG_070711_0003 "prohibition -den entering arena discharged."
#define STRMSG_070711_0004 "kullan Arena prohibited içiçinde \'%s\' kullanıcı."

///////////////////////////////////////////////////////////////////////////////
// 2007-08-23 by cmkwon, Wide 해상도 1280x720(16:9) 추가 - 스트링 추가
#define STRMSG_WINDOW_DEGREE_W1280x720_LOW			"1280x720 (low-wide)"
#define STRMSG_WINDOW_DEGREE_W1280x720_MEDIUM		"1280x720 (medium-wide)"
#define STRMSG_WINDOW_DEGREE_W1280x720_HIGH			"1280x720 (high-wide)"

// 2007-08-30 by cmkwon, 회의룸 시스템 구현 - 스트링 추가
#define STRMSG_070830_0001                                   "bu command -ebilir sadece be kullanıldı after ülke has been seçildi."
#define STRMSG_070830_0002                                   "Conference oda harita(%d) ilgili ülke değil mevcut"
#define STRMSG_070830_0003                                   "sayı users şu -ebilir gir conference oda: %dpeople(s)"
#define STRMSG_070830_0004                                   "'%s' has zaten been eklendi -e giriş list."
#define STRMSG_070830_0005                                   "'%s' does değil have giriş izin."
#define STRMSG_070830_0006                                   "'%s' değil geçerli karakter."
#define STRMSG_070830_0007                                 "'%s' cannot be eklendi -e conference oda giriş list.(maksimum %d people)"
#define STRMSG_070830_0008                                   "'%s' have alındı yetki entering conference oda."
#define STRMSG_070830_0009                                   "izin -e gir conference oda has been given."
#define STRMSG_070830_0010                                   "izin -e gir conference oda has been iptal edildi."
#define STRMSG_070830_0011                                   "'%s'"

// 2007-11-13 by cmkwon, just for Korean service, 
#define STRMSG_071115_0001									"\\y%s send siz %s as hediye."
#define STRMSG_071115_0002									"hediye list: \'%s(%d pieces)\'"
#define STRMSG_071115_0003									"\\y%s send hediye -e %s. hediye %s. lütfen kontrol edin depo."
 
// 2007-11-19 by cmkwon, callGM system 
#define STRMSG_071120_0001									"Appeal sistem değil içinde effect. lütfen kullanın customer centre."
#define STRMSG_071120_0002									"Appeal sistem activated."
#define STRMSG_071120_0003									"Appeal sistem concluded."
#define STRMSG_071120_0004									"Appeal sistem başlayacak -den %s -e %s."

// 2007-11-28 by cmkwon, 통지시스템 구현 - 
#define STRMSG_071128_0001									"%s has sent siz %s(%d) as hediye. lütfen kontrol edin sizin depo."

// 2007-12-27 by cmkwon, 윈도우즈 모드 기능 추가 - 
#define STRMSG_071228_0001				"çözünürlük setting geçersiz. lütfen kontrol edin again."

// 2008-01-31 by cmkwon, 계정 블럭/해제 명령어로 가능한 시스템 구현 - 
#define STRMSG_080201_0001									"'hata exists içinde %s' block setting. ErrorCode(%d)"
#define STRMSG_080201_0002									"'%s' hesap has been blocked.[Block End tarih: %s]"
#define STRMSG_080201_0003									"'%s' hesap does mevcut değil içinde block list. ErrorCode(%d)"
#define STRMSG_080201_0004									"'Erros has occured içinde process blocking %s' hesap. ErrorCode(%d)"
#define STRMSG_080201_0005									"'%s' hesap has been kaldırıldı -den block list." 

// 2008-02-11 by cmkwon, 해상도 추가(1440x900) - 
#define STRMSG_WINDOW_DEGREE_1440x900_LOW			"1440x900 (low-wide)"
#define STRMSG_WINDOW_DEGREE_1440x900_MEDIUM		"1440x900 (medium-wide)"
#define STRMSG_WINDOW_DEGREE_1440x900_HIGH			"1440x900 (high-wide)"

// 2007-12-27 by dhjin, 아레나통합- 아레나서버연결관련오류
#define STRMSG_S_MF2AFCONNECT_0000                       "[hata] WndProc(), -ebilir't connect -e ArenaServer[%15s:%4d] Reconnect\r\n"
#define STRMSG_S_MF2AFCONNECT_0001                       "bağlandı -e Arena sunucu.\r\n"
#define STRMSG_S_MF2AFCONNECT_0002                       "bağlantı -e Arena sunucu[%15s:%4d] kapalı. Trying -e re-connect.\r\n"
#define STRMSG_S_MF2AFCONNECT_0003                       "T_ERROR %s(%#04X) alındı -den %s[%s]\r\n"
#define STRMSG_S_MF2AFCONNECT_0004                       "bilinmeyen hata@WM_FIELD_PACKET_NOTIFY: %s(%#04x)\n"
#define STRMSG_ARENAEVENT_080310_0001                    "sayı \\y%d Arena waiting oda has been given etkinlik attribute.\r\n"
#define STRMSG_ARENAEVENT_080310_0002                    "sayı \\y%d Arena waiting oda has been discharged -den etkinlik attribute.\r\n"
#define STRMSG_ARENAEVENT_080310_0003                    "\\ybaşarısız oldu: give Arena attribute.\r\n"
#define STRMSG_080428_0001					"\\y%s has been shot down.\\y"          // 2008-04-28 by dhjin, Arena integration - String is added when taking down the opponent, only in Arena map 

// 2008-04-29 by cmkwon, 서버군 정보 DB에 추가(신규 계정 캐릭터 생성 제한 시스템추가) - 
#define STRMSG_080430_0001					"seçildi sunucu sunucu where creation new karakter değil mevcut."

// 2008-06-13 by dhjin, EP3 여단 수정 사항 - 
#define STRMSG_080613_0001					"Request içiçinde entering %s tugay rejected."

// 2008-09-04 by cmkwon, don't need translation, SystemLog 
#define STRMSG_080904_0001					 "[DB hata] yok such DB sorgu process(QP_xxx) function!! QueryType(%d:%s)\r\n"


// 2008-12-30 by cmkwon, 지도자 채팅 제한 카드 구현 - 
#define STRMSG_081230_0001					"\\y%s olacak restricted -den sohbet içiçinde %d dakika.\\y"
#define STRMSG_081230_0002					"\\ysohbet has been restricted tarafından leader içiçinde %d dakika.\\y"
#define STRMSG_081230_0003					"\\ysohbet restriction tarafından leader released.\\y"

///////////////////////////////////////////////////////////////////////////////
// 2009-08-31 by cmkwon, Gameforge4D 게임가드 동의창 띄우기 - 
// 2009-09-02 by cmkwon, Gameforge4D 게임 가드 동의창 WebPage로 처리 - STRMSG_090831_0001는 웹페이지로 처리
//#define STRMSG_090831_0001					"AirRivals is now protected from cheaters with a hackshield.\r\nPlease install it to help us to make AirRivals even safer.\r\nYou can only continue gameplay once you have installed the hackshield.\r\nPlease read the privacy policy< http://agb.gameforge.de/mmog/index.php?lang=en&art=datenschutz_mmog&special=airrivals&&f_text=b1daf2&f_text_hover=ffffff&f_text_h=061229&f_text_hr=061229&f_text_hrbg=061229&f_text_hrborder=9EBDE4&f_text_font=arial%2C+arial%2C+arial%2C+sans-serif&f_bg=000000 > to find out more about the hackshield's function."
#define STRMSG_090831_0002					"Install HackShield"
#define STRMSG_090831_0003					"cancel"

///////////////////////////////////////////////////////////////////////////////
// 2009-09-02 by cmkwon, Gameforge4D 게임 가드 동의창 WebPage로 처리 - 
#define STRMSG_090902_0001					"https://support.oldschoolrivals.com"

///////////////////////////////////////////////////////////////////////////////
// 2009-10-16 by cmkwon, 지원 해상도 추가(1680x1050,1920x1080,1920x1200) - 
#define STRMSG_WINDOW_DEGREE_1680x1050_LOW			"1680x1050 L"
#define STRMSG_WINDOW_DEGREE_1680x1050_MEDIUM		"1680x1050 M"
#define STRMSG_WINDOW_DEGREE_1680x1050_HIGH			"1680x1050 H"
#define STRMSG_WINDOW_DEGREE_1920x1080_LOW			"1920x1080 L"
#define STRMSG_WINDOW_DEGREE_1920x1080_MEDIUM		"1920x1080 M"
#define STRMSG_WINDOW_DEGREE_1920x1080_HIGH			"1920x1080 H"
#define STRMSG_WINDOW_DEGREE_1920x1200_LOW			"1920x1200 L"
#define STRMSG_WINDOW_DEGREE_1920x1200_MEDIUM		"1920x1200 M"
#define STRMSG_WINDOW_DEGREE_1920x1200_HIGH			"1920x1200 H"

///////////////////////////////////////////////////////////////////////////////
// 2011-01-26 by hskim, 인증 서버의 접속 허용 상황
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_NOT_REGISTER			"değil kaydoldu sunucu (It -ebilir be Illegal Private sunucu.)"
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_DB_ERROR				"hata occurs during linkage ile DB"
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_OK						"Authentication succeed"
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_BLOCKED				"kaydoldu sunucu IP ama proceed Authentication Denied"
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_SHUTDOWN				"Windows Shut Down command sent -e sunucu."

#endif // end_#ifndef _STRING_DEFINE_SERVER_H_
