//{{NO_DEPENDENCIES}}
// Plik do³¹czany wygenerowany przez œrodowisko Microsoft Visual C++.
// U¿ywany przez: AtumAdminTool.rc
//
#define ID_SEPARATOR                    0
#define VS_VERSION_INFO                 1
#define IDS_LOG_PRO_SHEET               1
#define IDC_BTN_RELOAD_HAPPYEV          2
#define IDC_BUTTON_RELOAD               3
#define IDC_BUTTON_CONNECT              3
#define IDC_BTN_INIT_TEXT               3
#define IDC_BUTTON_SAVE                 4
#define IDC_BUTTON_RESET                5
#define IDC_BUTTON_DISCONNECT           5
#define IDC_BUTTON_EDIT_CHARACTER       6
#define IDC_BUTTON_SELECT_ALL           6
#define IDC_BUTTON_BLOCK_ACCOUNT        7
#define IDC_BUTTON_DISELECT_ALL         7
#define IDC_BUTTON_UNBLOCK_ACCOUNT      8
#define IDC_BUTTON_SELECT_ITEM          8
#define IDC_BUTTON_EDIT_ACCOUNT         9
#define IDC_BUTTON_BLOCK_EDIT           10
#define IDC_BUTTON_EDIT_PREMIUM         11
#define IDC_BUTTON_DELETED_CHARACTER    12
#define AFX_IDC_LISTBOX                 100
#define AFX_IDC_CHANGE                  101
#define IDD_LOG_TAB_CONNECTION          101
#define AFX_IDC_BROWSER                 102
#define IDD_ATUMADMINTOOL_DIALOG        102
#define IDD_DIALOG_ATUM_ADMIN_TOOL      102
#define IDD_LOG_TAB_SERVERINTEGRATION   106
#define IDR_MAINFRAME                   128
#define IDD_SCUSERADMIN_DIALOG          129
#define IDD_DIALOG_USER_ADMIN_TOOL      129
#define IDD_DIALOG_SERVER_ADMIN_TOOL    130
#define IDR_CONTEXT_MENU_GRID_ITEM      131
#define IDR_CONTEXT_MENU_GRID_SERVER    133
#define IDR_WAVE_ALERT                  134
#define IDD_DIALOG_BAD_USER_ADMIN_TOOL  135
#define IDD_DIALOG_INSERT_ITEM          136
#define IDD_DIALOG_SELECT_ITEM          136
#define IDD_DIALOG_LOG_ADMIN_TOOL       137
#define IDD_DIALOG_MODIFY_ITEM          138
#define IDR_CONTEXT_MENU_GRID_BAD_USER  138
#define IDD_DIALOG_CHARACTER_INFO       139
#define IDD_DLG_BLOCK_ACCOUNT           140
#define IDD_DIALOG_CONNECT_SERVER       141
#define IDD_LOG_TAB_USER                141
#define IDD_LOG_TAB_ITEM                142
#define IDR_MENU_TRAY                   146
#define IDD_DIALOG_EDIT_ACCOUNT         148
#define IDD_DIALOG_PWD                  150
#define IDD_DLG_LOCALIZATION            151
#define IDD_DLG_PREMIUM                 152
#define IDD_DIALOG_HAPPY_HOUR_EVENT_ADMIN 153
#define IDD_DLG_EXP_VIEWER              157
#define IDD_DLG_GUILD_ADMIN             160
#define IDD_DLG_                        161
#define IDD_DLG_BLOCK_ACCOUNT_LIST      161
#define IDD_DLG_INFLWAR_LIST            162
#define IDD_DLG_SET_HAPPYEV             163
#define IDR_CONTEXT_MENU_HAPPYEV        165
#define IDD_DLG_SET_PCBANG_HAPPYEV      166
#define IDD_DIALOG_ITEM_EVENT_ADMIN     167
#define IDD_DLG_SET_ITEMEV              168
#define IDD_LOG_TAB_GUILDITEM           169
#define IDD_DLG_DELETED_CHARACTER       170
#define IDR_CONTEXT_MENU_DELETED_CHARACTER 172
#define IDD_DIALOG_STRATEGYPOINT_ADMIN_TOOL 173
#define IDD_DLG_EDIT_GUILD              175
#define IDD_DLG_GUILD_MARK_RECOGNITION  176
#define IDB_BITMAP_CHECK_IMAGE          177
#define IDD_DLG_XOR_TEST                178
#define IDD_DLG_LEADER_ELECTION         179
#define IDD_DLG_PETITION_MANAGEMENT     180
#define IDD_DLG_OUTPOST                 181
#define IDD_LOG_TAB_BLOCKACCOUNT        182
#define IDD_DLG_EVENT_MONSTER_MANAGEMENT 183
#define IDR_CONTEXT_MENU_EVENT_MONSTER_MENAGEMENT 184
#define IDD_DLG_EVENT_MONSTER           185
#define IDD_DLG_SET_LIMIT_USER_COUNT    186
#define IDD_DIALOG_ADMIN_AUTO_NOTICE    187
#define IDD_DLG_DECLARATION_OF_WAR      189
#define IDD_DLG_CASHSHOP_MANAGEMENT     191
#define IDD_DLG_WRK_MANAGEMENT          192
#define IDD_DLG_WRK_SERVICE_SETTING     193
#define IDD_DLG_WRK_UPDATE_RANKING      194
#define IDD_DLG_SET_INFLUENCE_RATE      195
#define IDD_DLG_MSGBOX                  196
#define IDD_DLG_XOR_TEST1               197
#define AFX_IDC_PRINT_DOCNAME           201
#define IDD_DLG_MULTINATION             201
#define AFX_IDC_PRINT_PRINTERNAME       202
#define AFX_IDC_PRINT_PORTNAME          203
#define AFX_IDC_PRINT_PAGENUM           204
#define IDB_BITMAP1                     207
#define IDB_BITMAP2                     208
#define IDB_BITMAP3                     209
#define IDD_DIALOG_RENEWAL_STRATEGYPOINT 210
#define IDB_BITMAP4                     210
#define IDB_BITMAP5                     211
#define IDB_BITMAP6                     212
#define IDB_BITMAP7                     213
#define IDB_BITMAP8                     214
#define IDB_BITMAP9                     215
#define IDB_BITMAP10                    216
#define IDB_BITMAP12                    218
#define IDB_BITMAP13                    219
#define IDB_BITMAP14                    220
#define IDB_BITMAP15                    221
#define IDB_BITMAP16                    222
#define IDB_BITMAP17                    223
#define IDB_BITMAP18                    224
#define IDB_BITMAP19                    225
#define IDB_BITMAP20                    226
#define IDI_ICON1                       227
#define IDD_DLG_MULTIACCOUNT            228
#define IDB_BITMAP21                    232
#define IDB_BITMAP22                    233
#define IDB_BITMAP11                    234
#define IDB_BITMAP23                    235
#define IDB_BITMAP24                    259
#define IDB_BITMAP25                    260
#define IDB_BITMAP26                    261
#define IDB_BITMAP27                    262
#define IDB_BITMAP28                    263
#define IDB_BITMAP29                    264
#define IDB_BITMAP30                    265
#define IDB_BITMAP31                    266
#define IDB_BITMAP32                    267
#define IDB_BITMAP33                    268
#define IDB_BITMAP34                    269
#define IDB_BITMAP35                    270
#define IDB_BITMAP36                    271
#define IDB_BITMAP37                    272
#define IDB_BITMAP38                    273
#define IDB_BITMAP39                    274
#define IDB_BITMAP40                    275
#define IDB_BITMAP41                    276
#define IDB_BITMAP42                    277
#define IDB_BITMAP43                    278
#define IDB_BITMAP44                    279
#define IDB_BITMAP45                    280
#define AFX_IDC_FONTPROP                1000
#define IDC_BUTTON_USER_TOOL            1000
#define IDC_STATIC_ACCOUNT              1000
#define AFX_IDC_FONTNAMES               1001
#define IDC_RADIO_ACCOUNT               1001
#define IDC_BUTTON_LOG_TOOL             1001
#define AFX_IDC_FONTSTYLES              1002
#define IDC_RADIO_CHARACTER             1002
#define IDC_BUTTON_HAPPY_HOUR_EVENT_TOOL 1002
#define AFX_IDC_FONTSIZES               1003
#define IDC_EDIT_USER_INPUT             1003
#define IDC_BUTTON_SERVER               1003
#define AFX_IDC_STRIKEOUT               1004
#define IDC_BUTTON_GET_USER_INFO        1004
#define IDC_STATIC_CONNECTION           1004
#define AFX_IDC_UNDERLINE               1005
#define IDC_EDIT_ACCNAME                1005
#define IDC_STATIC_TOOLS                1005
#define AFX_IDC_SAMPLEBOX               1006
#define IDC_EDIT_CHARAC_NAME_1          1006
#define IDC_COMBO_SERVER_               1006
#define IDC_BUTTON_SCREEN_SHOT_VIEWER   1006
#define IDC_EDIT_CHARAC_NAME_2          1007
#define IDC_EDIT_UID_                   1007
#define IDC_STATIC_TOOLS2               1007
#define IDC_EDIT_CHARAC_NAME_3          1008
#define IDC_EDIT_PWD_                   1008
#define IDC_BTN_GUILD_TOOL              1008
#define IDC_STATIC_ACCNAME              1009
#define IDC_BUTTON_ITEM_EVENT           1009
#define IDC_STATIC_CHARAC_1             1010
#define IDC_BUTTON_STRATEGYPOINT        1010
#define IDC_EDIT_POSITION               1011
#define IDC_BTN_PETITION_SYTEM          1011
#define IDC_BUTTON_CHARAC_1_OK          1012
#define IDC_GRID_SERVER_INFO            1012
#define IDC_BUTTON_OUTPOST              1012
#define IDC_EDIT_USER_COUNT             1012
#define IDC_STATIC_CHARAC_2             1013
#define IDC_COMBO1                      1013
#define IDC_BUTTON_EVENT_MONSTER        1013
#define IDC_STATIC_CHARAC_3             1014
#define IDC_EDIT_CHAT_MESSAGE           1014
#define IDC_STATIC_POSITION             1015
#define IDC_BUTTON_SEND_CHAT            1015
#define IDC_BUTTON_CHARAC_2_OK          1016
#define IDC_BUTTON_REFRESH              1016
#define IDC_BUTTON_CHARAC_3_OK          1017
#define IDC_EDIT_OUTPUT                 1017
#define IDC_BUTTON_STOP_SOUND           1018
#define IDC_BUTTON_LOAD_DATA            1018
#define IDC_EDIT_ACC_TYPE               1018
#define IDC_RADIO_ACCOUNT_UID           1019
#define IDC_BUTTON_BLOCK_USER           1020
#define IDC_RADIO_CHARACTER_UID         1020
#define IDC_STATIC_USER_INFO            1021
#define IDC_GRID_BAD_USER               1021
#define IDC_STATIC_BLOCK_PERIOD         1022
#define IDC_BUTTON_CHARAC_3_OK2         1022
#define IDC_BUTTON_CHARAC_4_OK          1022
#define IDC_STATIC_USER                 1023
#define IDC_EDIT_CHARAC_NAME_4          1023
#define IDC_STATIC_CHARAC_4             1024
#define IDC_GRID_ITEM                   1025
#define IDC_STATIC_ITEM_INFO            1026
#define IDC_COMBO_ITEM                  1027
#define IDC_STATIC_BLOCK_TYPE           1027
#define IDC_COMBO_ACC_OR_CHARAC_USER_TOOL 1027
#define IDC_COMBO_ACC_OR_CHARAC2        1027
#define IDC_STATIC_ITEM_INFO2           1027
#define IDC_COMBO_ITEM_KIND             1028
#define IDC_COMBO_BLOCK_TYPE            1028
#define IDC_TAB_LOG_ADMIN_TOOL          1028
#define IDC_EDIT_REASON                 1029
#define IDC_GRID_CONNECTION_LOG         1029
#define IDC_STATIC_BLOCK_REASON         1030
#define IDC_STATIC_ACC_TYPE             1030
#define IDC_STATIC_BLOCK_TYPE2          1030
#define IDC_EDIT_REASON_FOR_ONLY_ADMIN  1030
#define IDC_STATIC_ITEM_COUNT           1031
#define IDC_GRID_ITEM_LOG               1031
#define IDC_STATIC_ACC_TYPE2            1031
#define IDC_EDIT_ITEM_COUNT             1032
#define IDC_GRID_USER_LOG               1032
#define IDC_STATIC_SEX                  1032
#define IDC_EDIT_CHANNEL_INDEX          1033
#define IDC_STATIC_ACC_TYPE4            1033
#define IDC_EDIT_ITEM_NAME              1034
#define IDC_BUTTON_OK                   1034
#define IDC_STATIC_ACC_TYPE5            1034
#define IDC_PROPENSITY                  1035
#define IDC_STATIC_SEX2                 1035
#define IDC_BUTTON_OK2                  1035
#define IDC_COMBO_PREFIX                1036
#define IDC_STATIC_RACING_POINT         1036
#define IDC_EDIT_POS_Z                  1037
#define IDC_GRID_CHARACTER              1037
#define IDC_EDIT_CHARACTER_NAME         1038
#define IDC_COMBO_SUFFIX                1039
#define IDC_DATETIMEPICKER_START_DATE   1039
#define IDC_EDIT_PASSWORD               1039
#define IDC_EDIT_MAP_INDEX              1040
#define IDC_EDIT_SEX                    1040
#define IDC_COMBO_ADD_ENCHANT           1040
#define IDC_EDIT_POS_X                  1041
#define IDC_DATETIMEPICKER_END_DATE     1041
#define IDC_EDIT_REG_DATE               1041
#define IDC_COMBO_COLORCODE             1041
#define IDC_COMBO_RACE                  1042
#define IDC_CHECK_CHARACTER             1042
#define IDC_EDIT_LAST_LOGIN_DATE        1042
#define IDC_COMBO_SHAPEITEMNUM          1042
#define IDC_COMBO_RACE_ACC_TYPE         1043
#define IDC_CHECK_DATE                  1043
#define IDC_EDIT_BIRTH_YEAR             1043
#define IDC_EDIT_LEVEL                  1044
#define IDC_CHECK_MAX_ROW_COUNT         1044
#define IDC_COMBO_RACE_ACC_TYPE2        1044
#define IDC_EDIT_LANG_INFO              1044
#define IDC_EDIT_EXP_PER                1045
#define IDC_COMBO_SERVER                1045
#define IDC_CHECK_CHARACTER_ITEM        1045
#define IDC_CHECK_GUILDNAME             1045
#define IDC_EDIT_SECPASSWORD            1045
#define IDC_CHECK_BLOCK_DATE            1045
#define IDC_EDIT_LANG_TYPE              1045
#define IDC_EDIT_HP                     1046
#define IDC_EDIT_UID                    1046
#define IDC_EDIT_ACCOUNT_NAME           1046
#define IDC_EDIT_EMAIL                  1046
#define IDC_EDIT_DP                     1047
#define IDC_EDIT_PWD                    1047
#define IDC_CHECK_ACCOUNT_NAME          1047
#define IDC_EDIT_PASSWORD3              1047
#define IDC_EDIT_CASHPOINT              1047
#define IDC_EDIT_SP                     1048
#define IDC_EDIT_TOTAL_LOG_ROW_COUNT    1048
#define IDC_EDIT_CASHPOINT2             1048
#define IDC_EDIT_EP                     1049
#define IDC_EDIT_CHARACTER_NAME2        1049
#define IDC_EDIT_PART_ATTACK            1050
#define IDC_CHECK_CHARACTER2            1050
#define IDC_CHECK_LOG_LOGIN             1050
#define IDC_CHECK_ADMIN_ACCOUNT_NAME    1050
#define IDC_EDIT_ACCOUNT_NAME2          1051
#define IDC_CHECK_LOG_LOGOUT            1051
#define IDC_COMBO_INFLUENCETYPE         1051
#define IDC_CHECK_GET_ITEM              1052
#define IDC_CHECK_CHARACTERNAME         1052
#define IDC_EDIT_PART_ATTACK2           1052
#define IDC_CHECK_USE_ENERGY            1053
#define IDC_EDIT_PART_ATTACK3           1053
#define IDC_CHECK_TRADE_RECV            1054
#define IDC_EDIT_PART_ATTACK4           1054
#define IDC_EDIT_PART_DEFENSE           1055
#define IDC_CHECK_THROWAWAY_ITEM        1055
#define IDC_EDIT_BONUS_STAT             1056
#define IDC_CHECK_BUY_ITEM              1056
#define IDC_EDIT_PART_SOUL              1057
#define IDC_CHECK_USE_ITEM              1057
#define IDC_EDIT_PART_SHIELD            1058
#define IDC_CHECK_TRADE_SEND            1058
#define IDC_EDIT_PART_DODGE             1059
#define IDC_CHECK_USE_ENCHANT           1059
#define IDC_EDIT_HP_CUR                 1060
#define IDC_CHECK_ADD_ITEM_BY_ADMIN     1060
#define IDC_EDIT_DP_CUR                 1061
#define IDC_CHECK_DEL_ITEM_BY_ADMIN     1061
#define IDC_EDIT_SP_CUR                 1062
#define IDC_CHECK_ADD_ITEM_BY_COMMAND   1062
#define IDC_CHECK_USER_GAMESTART        1062
#define IDC_EDIT_EP_CUR                 1063
#define IDC_CHECK_SELL_ITEM             1063
#define IDC_EDIT_PART_FUEL              1064
#define IDC_CHECK_INSERT_TO_STORE       1064
#define IDC_CHECK_USER_GAMEEND          1064
#define IDC_EDIT_PROPENSITY             1065
#define IDC_CHECK_DRAW_FROM_STORE       1065
#define IDC_CHECK_USER_LEVEL_CHANGE     1065
#define IDC_EDIT_RACING_POINT           1066
#define IDC_CHECK_ALL                   1066
#define IDC_EDIT_SELECTED_ITEM          1066
#define IDC_CHECK_ACCOUNT_NAME2         1067
#define IDC_CHECK_USER_EXP_CHANGE       1067
#define IDC_EDIT_BONUS_STAT_POINT       1067
#define IDC_CHECK_USER_STAT_CHANGE      1068
#define IDC_CHECK_STORE_START_ITEM      1068
#define IDC_EDIT_PART_ATTACK5           1068
#define IDC_CHECK_USER_QUEST_END        1069
#define IDC_CHECK_GIFT_SEND             1069
#define IDC_EDIT_PART_ATTACK6           1069
#define IDC_CHECK_USER_PVP_WIN          1070
#define IDC_CHECK_GIFT_RECV             1070
#define IDC_EDIT_PART_ATTACK7           1070
#define IDC_CHECK_USER_PVP_LOSE         1071
#define IDC_CHECK_REARRANGEITEM_ITEM    1071
#define IDC_EDIT_PART_ATTACK8           1071
#define IDC_CHECK_USER_DEAD             1072
#define IDC_CHECK_ITEM_UID              1072
#define IDC_EDIT_PART_DEFENSE2          1072
#define IDC_CHECK_USER_WARP             1073
#define IDC_EDIT_ITEM_UID               1073
#define IDC_EDIT_PART_SOUL2             1073
#define IDC_CHECK_USER_SPEED_HACK       1074
#define IDC_CHECK_ITEM_NUM              1074
#define IDC_EDIT_PART_SHIELD2           1074
#define IDC_COMBO_CHAT_HISTORY          1075
#define IDC_CHECK_USER_CREATE_CHARACTER 1075
#define IDC_CHECK_REARRANGEITEM_DELETE  1075
#define IDC_EDIT_PART_DODGE2            1075
#define IDC_BUTTON_MD5_PWD              1076
#define IDC_CHECK_USER_MEMORY_HACK      1076
#define IDC_EDIT_PART_FUEL2             1076
#define IDC_CHECK_SELL_ITEM2            1076
#define IDC_CHECK_ACCOUNT_BLOCKED       1077
#define IDC_CHECK_USER_DELETE_CHARACTER 1077
#define IDC_CHECK_ITEMNUM               1077
#define IDC_CHECK_USE_ENCHANT2          1077
#define IDC_CHECK_CHATTING_BLOCKED      1078
#define IDC_CHECK_USER_PVE_WIN          1078
#define IDC_EDIT_ITEM_NUM               1078
#define IDC_CHECK_USER_PVE_LOSS         1079
#define IDC_BUTTON_MD5_SECPWD           1079
#define IDC_DATETIMEPICKER_START_TIME   1080
#define IDC_DATETIMEPICKER_END_TIME     1081
#define IDC_STATIC_TOTAL_USER_COUNT     1081
#define IDC_EDIT_SUNBCU                 1083
#define IDC_EDIT1                       1083
#define IDC_EDIT_EXP                    1083
#define IDC_EDIT_LOCALIZATION_PATH      1083
#define IDC_EDIT_LANGUAGE               1083
#define IDC_EDIT_ADMIN_NAME             1083
#define IDC_EDIT_ACCOUNTNAME            1083
#define IDC_EDIT_EXPRATE                1083
#define IDC_EDIT_TOTAL_EXP              1083
#define IDC_EDIT_ENCHNT_COUNT           1083
#define IDC_EDIT_SEARCH_GUILDNAME       1083
#define IDC_ITEMNUM_EDIT                1083
#define IDC_EDIT_SUMMON_RANGE           1083
#define IDC_EDIT_SOURCE_STRING          1083
#define IDC_EDIT_ELECTION_STATE         1083
#define IDC_EDIT_OUTPOSTMAP             1083
#define IDC_EDIT_REQ_MIN_LEVEL          1083
#define IDC_EDIT_LoopTime               1083
#define IDC_EDIT_STEP                   1083
#define IDC_EDIT_SERVICEUID             1083
#define IDC_EDIT_SUNANI                 1084
#define IDC_STATIC_EXP                  1084
#define IDC_EDIT_SPIRATE                1084
#define IDC_EDIT_ACCOUNTUID             1084
#define IDC_EDIT_SEARCH_GUILDUID        1084
#define IDC_EDIT_VOTE_NUMBER            1084
#define IDC_EDIT_CITYMAP                1084
#define IDC_EDIT_REQ_MAX_LEVEL          1084
#define IDC_EDIT_IntervalTime           1084
#define IDC_EDIT_SELECT                 1084
#define IDC_EDIT_SERVICE_NAME           1084
#define IDC_LEVELMIN                    1084
#define IDC_EDIT_MONBCU                 1085
#define IDC_EDIT_EXPREPAIRRATE          1085
#define IDC_EDIT_SOURCE_CHARACTER_NAME  1085
#define IDC_EDIT_MAPINDEX               1085
#define IDC_EDIT_SYMBOL_IMAGE_PATH      1085
#define IDC_LEVELMAX                    1085
#define IDC_EDIT_ACCOUNTNAME6           1085
#define IDC_EDIT_MONANI                 1086
#define IDC_RADIO_KOREAN                1086
#define IDC_EDIT_DROPITEMRATE           1086
#define IDC_EDIT_SOURCE_CHARACTER_UID   1086
#define IDC_EDIT_NEXTWARTIMESET         1086
#define IDC_EDIT_MONSTERNUM             1086
#define IDC_EDIT_SERVER_GROUP_ID        1086
#define IDC_EDIT_TUEBCU                 1087
#define IDC_RADIO_ENGLISH               1087
#define IDC_BTN_LOCALIZATION            1087
#define IDC_EDIT_DROPRAREITEMRATE       1087
#define IDC_EDIT_SOURCE_DB_NUM          1087
#define IDC_EDIT_INFLUENCE              1087
#define IDC_EDIT_MONSTER_COUNT          1087
#define IDC_EDIT_SERVER_GROUP_NAME      1087
#define IDC_EDIT_TUEANI                 1088
#define IDC_RADIO_JAPANESE              1088
#define IDC_EDIT_TARGET_CHARACTER_NAME  1088
#define IDC_EDIT_WPRATE                 1088
#define IDC_EDIT_GUILDUID               1088
#define IDC_EDIT_DELAY_TIME             1088
#define IDC_EDIT_ACCOUNTUID2            1088
#define IDC_EDIT_WEDBCU                 1089
#define IDC_RADIO_CHINESE               1089
#define IDC_DATETIMEPICKER_STARTDATE    1089
#define IDC_EDIT_TARGET_CHARACTER_UID   1089
#define IDC_EDIT_MINLEVEL               1089
#define IDC_EDIT_PROBABILITY            1089
#define IDC_EDIT_WEDANI                 1090
#define IDC_DATETIMEPICKER_STARTTIME    1090
#define IDC_BTN_INSERT                  1090
#define IDC_RADIO_VIETNAMESE            1090
#define IDC_EDIT_TARGET_DB_NUM          1090
#define IDC_EDIT_MAXLEVEL               1090
#define IDC_EDIT_MONSTERNUM2            1090
#define IDC_EDIT_WPRATE3                1090
#define IDC_EDIT_THUBCU                 1091
#define IDC_DATETIMEPICKER_ENDDATE      1091
#define IDC_BTN_UPDATE                  1091
#define IDC_EDIT_TOTAL_LOG_COUNTS       1091
#define IDC_EDIT_WPRATE2                1091
#define IDC_EDIT_THUANI                 1092
#define IDC_DATETIMEPICKER_ENDTIME      1092
#define IDC_BTN_DELETE                  1092
#define IDC_EDIT_ACCOUNTNAME2           1092
#define IDC_EDIT_FRIBCU                 1093
#define IDC_BTN_RELOAD                  1093
#define IDC_EDIT_ACCOUNTNAME3           1093
#define IDC_EDIT_FRIANI                 1094
#define IDC_DATETIMEPICKER_CREATED_DATE 1094
#define IDC_EDIT_ACCOUNTNAME4           1094
#define IDC_EDIT_SATBCU                 1095
#define IDC_DATETIMEPICKER_CREATED_TIME 1095
#define IDC_EDIT_ACCOUNTNAME5           1095
#define IDC_EDIT_SATANI                 1096
#define IDC_DATETIMEPICKER_UPDATED_DATE 1096
#define IDC_DATETIMEPICKER_UPDATED_TIME 1097
#define IDC_DATETIMEPICKER_EXPIRE_DATE  1098
#define IDC_DATETIMEPICKER_EXPIRE_TIME  1099
#define AFX_IDC_COLOR_BLACK             1100
#define IDC_COMBO_PREMIUM_ITEM          1100
#define AFX_IDC_COLOR_WHITE             1101
#define AFX_IDC_COLOR_RED               1102
#define AFX_IDC_COLOR_GREEN             1103
#define AFX_IDC_COLOR_BLUE              1104
#define IDC_GRID_EVENT_TOTAL            1104
#define AFX_IDC_COLOR_YELLOW            1105
#define IDC_GRID_EVENT_DETAIL           1105
#define AFX_IDC_COLOR_MAGENTA           1106
#define IDC_GRID_SET_FOR_ALL            1106
#define AFX_IDC_COLOR_CYAN              1107
#define IDC_DATETIMEPICKER1             1107
#define AFX_IDC_COLOR_GRAY              1108
#define IDC_DATETIMEPICKER2             1108
#define AFX_IDC_COLOR_LIGHTGRAY         1109
#define IDC_DATETIMEPICKER3             1109
#define AFX_IDC_COLOR_DARKRED           1110
#define IDC_DATETIMEPICKER4             1110
#define AFX_IDC_COLOR_DARKGREEN         1111
#define IDC_DATETIMEPICKER5             1111
#define IDC_DATETIMEPICKER_DETAIL_STARTDATE 1111
#define IDC_DATEPICKER_PCBANG_START     1111
#define IDC_DATETIMEPICKER_LAST_DATE    1111
#define AFX_IDC_COLOR_DARKBLUE          1112
#define IDC_BUTTON_TOTALSET_REFRESH     1112
#define IDC_TIMEPICKER_PCBANG_START     1112
#define IDC_DATETIMEPICKER_LAST_TIME    1112
#define AFX_IDC_COLOR_LIGHTBROWN        1113
#define IDC_BUTTON_DETAIL_REFRESH       1113
#define IDC_DATEPICKER_PCBANG_END       1113
#define AFX_IDC_COLOR_DARKMAGENTA       1114
#define IDC_BUTTON_TOTAL_UPDATE         1114
#define AFX_IDC_COLOR_DARKCYAN          1115
#define IDC_BUTTON_TOTAL_INSERT         1115
#define IDC_TIMEPICKER_PCBANG_END       1115
#define AFX_IDC_COLORPROP               1116
#define IDC_BUTTON_TOTAL_DELETE         1116
#define IDC_BTN_UPDATE_PCBANG_HAPPYEV   1116
#define AFX_IDC_SYSTEMCOLORS            1117
#define IDC_DATETIMEPICKER6             1117
#define IDC_DATETIMEPICKER_DETAIL_STARTTIME 1117
#define IDC_DATEPICKER_NORMAL_START     1117
#define IDC_DATETIMEPICKER7             1118
#define IDC_TIMEPICKER_NORMAL_START     1118
#define IDC_DATETIMEPICKER8             1119
#define IDC_DATETIMEPICKER_DETAIL_ENDTIME 1119
#define IDC_DATEPICKER_NORMAL_END       1119
#define IDC_BUTTON_TOTAL_UPDATE2        1120
#define IDC_BUTTON_DETAIL_UPDATE        1120
#define IDC_TIMEPICKER_NORMAL_END       1120
#define IDC_BUTTON_TOTAL_INSERT2        1121
#define IDC_BUTTON_DETAIL_INSERT        1121
#define IDC_BTN_UPDATE_PERIOD_NORMAL    1121
#define IDC_BUTTON_TOTAL_DELETE2        1122
#define IDC_BUTTON_DETAIL_DELETE        1122
#define IDC_DATEPICKER_VCN_START        1122
#define IDC_BUTTON_TOTALSET_SELECT      1123
#define IDC_TIMEPICKER_VCN_START        1123
#define IDC_BUTTON_DETAIL_SELECT        1124
#define IDC_DATEPICKER_VCN_END          1124
#define IDC_COMBO_DETAIL_DAYOFWEEK      1125
#define IDC_TIMEPICKER_VCN_END          1125
#define IDC_BUTTON_END                  1126
#define IDC_COMBO_SERVER_GROUP          1126
#define IDC_BTN_SAVE_RESULT             1127
#define IDC_DATEPICKER_ANI_START        1127
#define IDC_COMBO_INFLUENCE_TYPE_LIST   1127
#define IDC_TIMEPICKER_ANI_START        1128
#define IDC_DATEPICKER_ANI_END          1129
#define IDC_BTN_EXP_VIEWER              1130
#define IDC_TIMEPICKER_ANI_END          1130
#define IDC_BTN_TO_LEVEL                1131
#define IDC_BTN_XOR_ENCODE              1131
#define IDC_BTN_UPDATE_PERIOD_ANI       1131
#define IDC_BTN_UPDATE_PERIOD_VCN       1132
#define IDC_BTN_XOR_ENCODE2             1132
#define IDC_EDIT_PERCENT                1133
#define IDC_BTN_TO_EXP                  1134
#define IDC_STATIC_INFLUENCETYPE        1136
#define IDC_BTN_SELECT_PATH             1137
#define IDC_GRID_GUILD                  1138
#define IDC_GRID_GUILDMEMBER            1139
#define IDC_BTN_SEARCHGUILD             1140
#define IDC_GRID_BLOCKED_LIST           1141
#define IDC_GRID_GUILDITEMS             1141
#define IDC_BTN_BLOCKED_LIST            1142
#define IDC_BTN_SEARCHGUILD_BYGUID      1142
#define IDC_BTN_RELOAD_ACCOUNT_BLOCKED_LIST 1144
#define IDC_BTN_INFLWAR_LIST            1145
#define IDC_GRID_INFLWAR_LIST           1146
#define IDC_BTN_RELOAD_INFLWARDATA_LIST 1147
#define IDC_CHECK_SET_INFL_LEADER       1148
#define IDC_BTN_INIT_INFL_DATA          1149
#define IDC_BTN_INIT_MONTHLY_GUILDFAME  1150
#define IDC_CHECK_Bazaar_Sell           1150
#define IDC_CHECK_Bazaar_Buy            1151
#define IDC_BTN_LEADER_ELECTION         1151
#define IDC_BTN_DEFAULT_VALUES          1152
#define IDC_BTN_DECLARATION_OF_WAR      1152
#define IDC_GRID_ITEM_EVENT_LIST        1155
#define IDC_CHECK1                      1156
#define IDC_ITEM_EVENT_TYPE_OnlyOne_CHECK 1156
#define IDC_CHECKSubLeader              1156
#define IDC_CHECK_AccountName           1156
#define IDC_CHECK_IP_ADDRESS            1156
#define IDC_SUMMON_CHECK_SUNDAY         1156
#define IDC_CHECK_EXCEPT_OBJ_MON        1156
#define IDC_CHECK_SetForLevel           1156
#define IDC_CHECK2                      1157
#define IDC_PCBANG_CHECK                1157
#define IDC_CHECKInflSub2Leader         1157
#define IDC_CHECK_AccountUID            1157
#define IDC_CHECK_EXCEPT_INFL_MON       1157
#define IDC_CHECK_SetForAll             1157
#define IDC_EDIT2                       1158
#define IDC_COUNT_EDIT                  1158
#define IDC_CHECK_SOURCE_CHARACTER_NAME 1158
#define IDC_EDIT_STRATEGYPOINT_SUMMON_CHECK 1158
#define IDC_EDIT_PCBangTotalPlayTime    1158
#define IDC_EDIT_ENCOEDED_STRING        1158
#define IDC_CHECK_EXCEPT_NOT_ATTACK_MON 1158
#define IDC_EDIT_INSERT_ENCHANT_COUNT   1158
#define IDC_CHECK3                      1158
#define IDC_CHECK_AccountName6          1158
#define IDC_SET_ITEM_EVENT_BUTTON_OK    1159
#define IDC_CHECK_SOURCE_CHARACTER_UID  1159
#define IDC_CHECK8                      1159
#define IDC_ITEM_EVENT_TYPE_OneDay_CHECK 1160
#define IDC_ITEM_EVENT_ADMIN_TOOL_BUTTON_OK 1160
#define IDC_CHECK_SOURCE_DB_NUM         1160
#define IDC_RELOAD_ITEM_EVENT_BUTTON    1161
#define IDC_ITEM_EVENT_TYPE_INFL_NORMAL_CHECK 1161
#define IDC_CHECK_TARGET_CHARACTER_NAME 1161
#define IDC_CHECK_AccountUID2           1161
#define IDC_ITEM_EVENT_TYPE_INFL_VCN_CHECK 1162
#define IDC_CHECK_GUILD_UID             1162
#define IDC_CHECK_TARGET_CHARACTER_UID  1162
#define IDC_ITEM_EVENT_TYPE_INFL_ANI_CHECK 1163
#define IDC_CHECK_ITEMNAME              1163
#define IDC_CHECK_TARGET_DB_NUM         1163
#define IDC_ITEM_EVENT_TYPE_INFL_ALL_CHECK 1164
#define IDC_CHECK_INSERT_GUILDSTORE     1164
#define IDC_CHECK_AccountName2          1164
#define IDC_CHECK_DRAW_GUILDSTORE       1165
#define IDC_MEMBERSHIP_CHECK            1165
#define IDC_CHECK_AccountName3          1165
#define IDC_BUTTON_SEARCH               1166
#define IDC_ITEM_EVENT_TYPE_UNITKIND_BGEAR_CHECK 1166
#define IDC_SUMMON_CHECK_SATURDAY       1166
#define IDC_EDIT_GUILD_UID              1167
#define IDC_ITEM_EVENT_TYPE_UNITKIND_MGEAR_CHECK 1167
#define IDC_CHECK_AccountName4          1167
#define IDC_EDIT_GUILD_NAME             1168
#define IDC_ITEM_EVENT_TYPE_UNITKIND_AGEAR_CHECK 1168
#define IDC_SUMMON_CHECK_FRIDAY         1168
#define IDC_CHECK_AccountName5          1168
#define IDC_BTN_RELOAD_PCBANG_LIST      1169
#define IDC_ITEM_EVENT_TYPE_INFLCHANGE  1169
#define IDC_BTN_RELOAD_HAPPYHOUREV      1170
#define IDC_GRID_SERVERINTEGRATION_LOG  1170
#define IDC_ITEM_EVENT_TYPE_LEVELUP     1170
#define IDC_LEVEL_EDIT                  1171
#define IDC_SUMMON_CHECK_THURSDAY       1171
#define IDC_NEWMEMBER_CHECK             1172
#define IDC_SUMMON_CHECK_WEDNESDAY      1172
#define IDC_GRID_DELETED_CHARACTER_LIST 1173
#define IDC_ITEM_EVENT_TYPE_COUPON_ONLYONE 1173
#define IDC_SUMMON_CHECK_TUESDAY        1173
#define IDC_GRID_STRATEGYPOINT_RANGE_LIST 1174
#define IDC_ITEM_EVENT_TYPE_UNITKIND_IGEAR_CHECK 1174
#define IDC_GRID_STRATEGYPOINT_INFO_LIST 1175
#define IDC_ITEM_EVENT_TYPE_COUPON_ONEDAY 1175
#define IDC_BUTTON_STRATEGYPOINT_SUMMON_RANGE 1176
#define IDC_CHECKNUMBER_EDIT            1176
#define IDC_BUTTON_STRATEGYPOINT_SUMMON_RANGE_INIT 1177
#define IDC_EDIT_MAX_SUMMON_COUNT_DAILY 1178
#define IDC_DATETIME_SSUNDAY            1179
#define IDC_DATETIME_SUNENDTIME         1180
#define IDC_DATETIME_ESUNDAY            1180
#define IDC_DATETIME_MONSTARTTIME       1181
#define IDC_DATETIME_SMONDAY            1181
#define IDC_DATETIME_MONENDTIME         1182
#define IDC_DATETIME_EMONDAY            1182
#define IDC_DATETIME_TUESTARTTIME       1183
#define IDC_DATETIME_STUESDAY           1183
#define IDC_DATETIME_TUEENDTIME         1184
#define IDC_DATETIME_ETUESDAY           1184
#define IDC_DATETIME_WEDSTARTTIME       1185
#define IDC_DATETIME_SWEDNESDAY         1185
#define IDC_DATETIME_WEDENDTIME         1186
#define IDC_DATETIME_EWEDNESDAY         1186
#define IDC_DATETIME_THUSTARTTIME       1187
#define IDC_DATETIME_STHURSDAY          1187
#define IDC_DATETIME_THUENDTIME         1188
#define IDC_DATETIME_ETHURSDAY          1188
#define IDC_DATETIME_FRISTARTTIME       1189
#define IDC_DATETIME_SFRIDAY            1189
#define IDC_DATETIME_FRIENDTIME         1190
#define IDC_DATETIME_EFRIDAY            1190
#define IDC_DATETIME_SATSTARTTIME       1191
#define IDC_DATETIME_SSATURDAY          1191
#define IDC_DATETIME_SATENDTIME         1192
#define IDC_DATETIME_ESATURDAY          1192
#define IDC_BUTTON_UPDATE_STRATEGYPOINT_NOTSUMMONTIME 1193
#define IDC_SUMMON_CHECK_MONDAY         1194
#define IDC_EDIT_ARENA_WP               1195
#define IDC_EDIT_ARENA_WIN              1196
#define IDC_COMBO_ITEMEVENT_PREFIX      1196
#define IDC_EDIT_ARENA_DISCONNECT       1197
#define IDC_COMBO_ITEMEVENT_SUFFIX      1197
#define IDC_BTN_EDIT_GUILD              1197
#define IDC_EDIT_ARENA_LOSE             1198
#define IDC_BTN_GUILD_MARK_RECOGNITION  1198
#define IDC_EDIT_ARENA_CWP              1199
#define IDC_GRID_GUILD_MARK_LIST        1199
#define IDC_COMBO_GUILD_MARK_STATE      1200
#define AFX_IDC_PROPNAME                1201
#define AFX_IDC_PICTURE                 1202
#define IDC_EDIT_KEY_STRING             1202
#define AFX_IDC_BROWSE                  1203
#define IDC_APPLICATION_DATESTART       1203
#define AFX_IDC_CLEAR                   1204
#define IDC_APPLICATION_TIMESTART       1204
#define IDC_APPLICATION_DATEEND         1205
#define IDC_APPLICATION_TIMEEND         1206
#define IDC_VOTE_DATESTART              1207
#define IDC_VOTE_TIMESTART              1208
#define IDC_VOTE_DATEEND                1209
#define IDC_VOTE_TIMEEND                1210
#define IDC_ELECTION_DATE               1211
#define IDC_ELECTION_TIME               1212
#define IDC_BTN_AUTO_EDIT               1213
#define IDC_BTN_GM_EDIT                 1214
#define IDC_BTN_RESULT                  1215
#define IDC_BTN_OK                      1216
#define IDC_GRID_VOTE_RESULT_LIST       1217
#define IDC_STATIC_ALL                  1218
#define ID_UPDATE_TO_DB                 1218
#define IDC_STATIC_VCN                  1219
#define IDC_GRID_WPSHOP_LIST            1219
#define IDC_STATIC_ANI                  1220
#define ID_UPDATE_TO_DB2                1220
#define IDC_STATIC_NORMAL               1221
#define ID_UPDATE_TO_DB3                1221
#define IDC_BTN_IMMEDIAT_ON             1222
#define IDC_BTN_IMMEDIAT_OFF            1223
#define IDC_BTN_PERIOD_SETTING          1224
#define IDC_DTPICKER_START_DATE         1225
#define IDC_DTPICKER_START_TIME         1226
#define IDC_DTPICKER_END_DATE           1227
#define IDC_DTPICKER_END_TIME           1228
#define IDC_IPADDRESS                   1229
#define IDC_GRID_OUTPOST_INFO_LIST      1230
#define IDC_DATETIMEPICKER_GETDATE      1231
#define IDC_DATETIMEPICKER_GETTIME      1232
#define IDC_DATETIMEPICKER_NEXTWARDATE  1233
#define IDC_DATETIMEPICKER_NEXTWARTIME  1234
#define IDC_BUTTON_SELECT               1235
#define IDC_BUTTON_UPDATE               1236
#define IDC_CHECK_LOG_BLOCK             1236
#define IDC_CHECK_LOG_UNBLOCK           1237
#define IDC_CHECK_BLOCKEDTYPE           1238
#define IDC_GRID_BLOCKACCOUNT_LOG       1239
#define IDC_EDIT_ADMIN_ACCOUNT_NAME     1240
#define IDC_EDIT_MAX_ROW_COUNT          1241
#define IDC_CHECK_LAST_GAME_END_DATE    1242
#define IDC_GRID_EVENT_MONSTER_LIST     1244
#define IDC_BUTTON_LUCKYMACHINE_INIT    1246
#define IDC_BUTTON_AUTO_NOTICE          1247
#define IDC_BTN_CASHSHOP_MANAGEMENT     1248
#define IDC_ADMIN_AUTO_NOTICE_LIST      1249
#define IDC_BTN_WRANKING_MANAGEMENT     1249
#define IDC_NOTICE_UP                   1250
#define IDC_BTN_INFINITY                1250
#define IDC_NOTICE_DOWN                 1251
#define IDC_BTN_MULTINATIONDLG          1251
#define IDC_NOTICE_ADD                  1252
#define IDC_BTN_MULTINATIONDLG2         1252
#define IDC_NOTICE_DELETE               1253
#define IDC_BTN_GAMESERVER_RELOAD       1254
#define IDC_RADIO_YES                   1255
#define IDC_RADIO_NO                    1256
#define IDC_BTN_UPDATE_DB               1257
#define IDC_GRID_DECLARATION_OF_WAR_LIST 1257
#define IDC_STEP_DATESTART              1258
#define IDC_STEP_TIMESTART              1259
#define IDC_FORBID_DATESTART            1260
#define IDC_BUTTON_STEP_SELECT          1261
#define IDC_BUTTON_STEP_START_UPDATE    1262
#define IDC_FORBID_TIMESTART            1263
#define IDC_BUTTON_FORBID_UPDATE        1264
#define IDC_GRID_CUR_ITEM               1264
#define IDC_FORBID_DATEEND              1265
#define IDC_GRID_CHANGED_ITEM           1265
#define IDC_FORBID_TIMESTART2           1265
#define IDC_FORBID_TIMEEND              1266
#define IDC_BTN_UPDATE_TO_DB            1266
#define IDC_BTN_DELETE_FROM_CHANGED     1267
#define IDC_BTN_SERVICE_SETTING         1268
#define IDC_BTN_UPDATE_RANKING          1269
#define IDC_BTN_REG_OR_UPDATE           1269
#define IDC_MS_DATESTART                1270
#define IDC_BTN_DELETE_SERVICE          1270
#define IDC_MS_TIMESTART                1271
#define IDC_FIND_FILE                   1271
#define IDC_BUTTON_MS_START_UPDATE      1272
#define IDC_BTN_UPDATE_SERVICE          1272
#define IDC_BTN_UPDATE_SERVER_GROUP_NAME 1272
#define IDC_BTN_ARRANGE_LOCAL_RANKING   1273
#define IDC_BTN_DELETE_SERVER_GROUP_INFO 1273
#define IDC_BTN_INIT_INFLUENCE          1273
#define IDC_BTN_UPDATE_WRANKING         1274
#define IDC_BTN_SET_InfluenceRate       1274
#define IDC_BTN_RELOAD_WRANKING         1275
#define IDC_GRID_SET_FOR_LEVEL          1275
#define IDC_BTN_INFINITY_RESET_IMPUTE   1275
#define IDC_BTN_DOWNLOAD_WRANKING       1276
#define IDC_CHECK_CHECK_WITH_ACCOUNTUID 1276
#define IDC_CHECK_CHECK_WITH_CHARACTERUID 1277
#define IDC_STATIC_QUESTION             1277
#define IDC_BTN_FOR_TESTSERVER          1278
#define IDC_COMBO_ENCHANT_ITEMNUM_LIST  1279
#define IDC_ITEM_EVENT_TYPE_LOGINEVENT  1282
#define IDC_EDIT3                       1283
#define IDC_CHECK_ACTIVE_ACC            1284
#define IDC_RADIO1                      1285
#define IDC_RADIO2                      1286
#define IDC_RADIO3                      1287
#define IDC_RADIO4                      1288
#define IDC_RADIO5                      1289
#define IDC_RADIO6                      1290
#define IDC_RADIO7                      1291
#define IDC_RADIO8                      1292
#define IDC_RADIO9                      1293
#define IDC_RADIO10                     1294
#define IDC_RADIO11                     1295
#define IDC_RADIO12                     1296
#define IDC_RADIO13                     1297
#define IDC_RADIO14                     1298
#define IDC_RADIO15                     1299
#define IDC_RADIO16                     1300
#define IDC_RADIO17                     1301
#define IDC_RADIO18                     1302
#define IDC_RADIO19                     1303
#define IDC_RADIO20                     1304
#define IDC_SLIDER1                     1305
#define IDC_CHECK4                      1306
#define IDC_RADIO21                     1306
#define IDC_RADIO22                     1307
#define IDC_CHECK5                      1307
#define IDC_RECT                        1308
#define IDC_CHECK6                      1308
#define IDC_RADIO23                     1308
#define IDC_CHECK7                      1309
#define IDC_RADIO24                     1309
#define IDC_RADIO25                     1310
#define IDC_RADIO26                     1311
#define IDC_BUTTON1                     1312
#define IDC_BUTTON2                     1313
#define IDC_BUTTON3                     1314
#define IDC_BUTTON4                     1315
#define IDC_BUTTON5                     1316
#define IDC_RADIO27                     1316
#define IDC_BUTTON6                     1317
#define IDC_RADIO28                     1317
#define IDC_BUTTON7                     1318
#define IDC_RADIO29                     1318
#define IDC_RADIO30                     1319
#define IDC_BUTTON_SETTING_SAVE         1320
#define IDC_BUTTON_STRATEGYPOINT_APPLY  1320
#define IDC_RADIO31                     1320
#define IDC_BUTTON_LIST_LOAD            1321
#define IDC_RADIO32                     1321
#define IDC_BUTTON_LIST_SAVE            1322
#define IDC_RADIO33                     1322
#define IDC_DATETIME_SUNSTARTTIME       1323
#define IDC_RADIO34                     1323
#define IDC_GRID_STRATEGYPOINT_TODAY_LIST 1324
#define IDC_RADIO35                     1324
#define IDC_BUTTON_STRATEGYPOINT_SAVE   1325
#define IDC_RADIO36                     1325
#define ID_MENUITEM_SUMMON              1326
#define IDC_RADIO37                     1326
#define ID_MENUITEM_CANCEL              1327
#define IDC_RADIO38                     1327
#define IDR_CONTEXT_MENU_STRATEGYPOINT  1328
#define IDC_RADIO39                     1328
#define IDC_GRID_MULTIACC_LIST          1329
#define IDC_RADIO40                     1329
#define IDD_BALANCECHART                1330
#define IDC_RADIO41                     1330
#define IDC_CHART                       1331
#define IDC_RADIO42                     1331
#define IDC_BUTTON_CHART_RLD            1332
#define IDC_RADIO43                     1332
#define IDC_DATETIMEPICKER1_CHART       1333
#define IDC_RADIO44                     1333
#define IDC_DATETIMEPICKER2_CHART       1334
#define IDC_RADIO45                     1334
#define IDC_BUTTON8                     1334
#define IDC_BUTTON_CHART_RLD2           1335
#define IDC_BUTTON9                     1335
#define IDC_BUTTON_CHART_RLD3           1336
#define AFX_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define AFX_IDD_NEWTYPEDLG              30721
#define AFX_IDD_PRINTDLG                30722
#define AFX_IDD_PREVIEW_TOOLBAR         30723
#define AFX_IDD_INSERTOBJECT            30724
#define AFX_IDD_CHANGEICON              30725
#define AFX_IDD_CONVERT                 30726
#define AFX_IDD_PASTESPECIAL            30727
#define AFX_IDD_EDITLINKS               30728
#define AFX_IDD_FILEBROWSE              30729
#define AFX_IDD_BUSY                    30730
#define AFX_IDD_OBJECTPROPERTIES        30732
#define AFX_IDD_CHANGESOURCE            30733
#define AFX_IDD_EMPTYDIALOG             30734
#define AFX_IDC_CONTEXTHELP             30977
#define AFX_IDC_MAGNIFY                 30978
#define AFX_IDC_SMALLARROWS             30979
#define AFX_IDC_HSPLITBAR               30980
#define AFX_IDC_VSPLITBAR               30981
#define AFX_IDC_NODROPCRSR              30982
#define AFX_IDC_TRACKNWSE               30983
#define AFX_IDC_TRACKNESW               30984
#define AFX_IDC_TRACKNS                 30985
#define AFX_IDC_TRACKWE                 30986
#define AFX_IDC_TRACK4WAY               30987
#define AFX_IDC_MOVE4WAY                30988
#define AFX_IDB_MINIFRAME_MENU          30994
#define AFX_IDB_CHECKLISTBOX_95         30996
#define AFX_IDR_PREVIEW_ACCEL           30997
#define AFX_IDC_MOUSE_PAN_NW            30998
#define AFX_IDC_MOUSE_PAN_N             30999
#define AFX_IDC_MOUSE_PAN_NE            31000
#define AFX_IDC_MOUSE_PAN_W             31001
#define AFX_IDC_MOUSE_PAN_HV            31002
#define AFX_IDC_MOUSE_PAN_E             31003
#define AFX_IDC_MOUSE_PAN_SW            31004
#define AFX_IDC_MOUSE_PAN_S             31005
#define AFX_IDC_MOUSE_PAN_SE            31006
#define AFX_IDC_MOUSE_PAN_HORZ          31007
#define AFX_IDC_MOUSE_PAN_VERT          31008
#define AFX_IDC_MOUSE_ORG_HORZ          31009
#define AFX_IDC_MOUSE_ORG_VERT          31010
#define AFX_IDC_MOUSE_ORG_HV            31011
#define AFX_IDC_MOUSE_MASK              31012
#define AFX_IDI_STD_MDIFRAME            31233
#define AFX_IDI_STD_FRAME               31234
#define AFX_IDD_PROPPAGE_COLOR          32257
#define AFX_IDD_PROPPAGE_FONT           32258
#define AFX_IDD_PROPPAGE_PICTURE        32259
#define ID_CMG_INSERT_ITEM              32771
#define ID_CMG_SERVER_GET_ACCOUNT_LIST  32771
#define ID_CMG_DELETE_ITEM              32772
#define ID_CMG_BLOCK_ACCOUNT            32772
#define ID_CMG_MODIFY_ITEM              32773
#define ID_CMG_BLOCK_CHATTING           32773
#define ID_CMG_UNBLOCK                  32774
#define ID_CMG_DELETE_BLOCKED_USER      32775
#define ID_MENU_TRAY_OPEN               32776
#define ID_MENU_TRAY_EXIT               32777
#define ID_CMG_ITEM_INFORMATION         32778
#define IDR_CONMENU_SELECTED_INSERT     32779
#define IDR_CONMENU_SELECTED_UPDATE     32780
#define IDR_CONMENU_SELECTED_DELETE     32781
#define IDR_CONMENU_NOTSELECTED_INSERT  32782
#define IDR_CONMENU_SELECTED_DELETE_CHARACTER 32783
#define ID_CONMENU_ADD_EVENT_MONSTER    32784
#define ID_CONMENU_MODIFY_EVENT_MONSTER 32785
#define ID_CONMENU_DELETE_EVENT_MONSTER 32786
#define ID_CMG_SET_LIMIT_USER_COUNT     32787
#define ID_CMG_CHANGE_LOCK_CREATE_CHARACTER_FOR_NEW_ACCOUNT 32788
#define ID_CMG_SERVER_RELOAD_INFLUENCE_RATE 32789
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define AFX_IDS_APP_TITLE_EMBEDDING     0xE003
#define AFX_IDS_COMPANY_NAME            0xE004
#define AFX_IDS_OBJ_TITLE_INPLACE       0xE005
#define AFX_IDS_APP_ID                  0xE006
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_NEW_FRAME               0xE10D
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_FORMAT_FONT                  0xE160
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_OLE_VERB_POPUP               0xE220
#define AFX_ID_PREVIEW_CLOSE            0xE300
#define AFX_ID_PREVIEW_NUMPAGE          0xE301
#define AFX_ID_PREVIEW_NEXT             0xE302
#define AFX_ID_PREVIEW_PREV             0xE303
#define AFX_ID_PREVIEW_PRINT            0xE304
#define AFX_ID_PREVIEW_ZOOMIN           0xE305
#define AFX_ID_PREVIEW_ZOOMOUT          0xE306
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_INDICATOR_KANA               0xE706
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REBAR                   0xE804
#define ID_VIEW_AUTOARRANGE             0xE805
#define ID_VIEW_SMALLICON               0xE810
#define ID_VIEW_LARGEICON               0xE811
#define ID_VIEW_LIST                    0xE812
#define ID_VIEW_DETAILS                 0xE813
#define ID_VIEW_LINEUP                  0xE814
#define ID_VIEW_BYNAME                  0xE815
#define ID_RECORD_FIRST                 0xE900
#define ID_RECORD_LAST                  0xE901
#define ID_RECORD_NEXT                  0xE902
#define ID_RECORD_PREV                  0xE903
#define AFX_TIMER_ID_FIRST              0xEC00
#define AFX_TIMER_ID_DISPLAY_AHWND_EVENT 0xEC00
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_IN_EVENT 0xEC01
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_OUT_EVENT 0xEC02
#define AFX_TIMER_ID_CHECK_AUTO_HIDE_CONDITION 0xEC03
#define AFX_TIMER_ID_DOCK_EVENT         0xEC04
#define AFX_TIMER_ID_CHECK_ROLL_STATE   0xEC05
#define AFX_TIMER_ID_VISIBILITY_TIMER   0xEC06
#define AFX_TIMER_ID_ACCELERATOR_NOTIFY_EVENT 0xEC07
#define AFX_TIMER_ID_TIMER_TRACKING     0xEC08
#define AFX_TIMER_ID_TIMER_WAIT         0xEC09
#define AFX_TIMER_ID_TIMER_CHECK        0xEC0A
#define AFX_TIMER_ID_TASK_ANIMATION     0xEC0B
#define AFX_TIMER_ID_TASK_SCROLL        0xEC0C
#define AFX_TIMER_ID_AUTOCOMMAND        0xEC0D
#define AFX_TIMER_ID_ALERT_CLOSE_POPUP  0xEC0E
#define AFX_TIMER_ID_ALERT_ANIMATION    0xEC0F
#define AFX_TIMER_ID_ALERT_CHECK_ACTIVITY 0xEC10
#define AFX_TIMER_ID_TB_SHOW_DROPDOWN   0xEC11
#define AFX_TIMER_ID_MENU_SHOW_ALL_ITEMS 0xEC12
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_UP 0xEC13
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_DN 0xEC14
#define AFX_TIMER_ID_MENU_POPUP_ANIMATION 0xEC15
#define AFX_TIMER_ID_MENU_POPUP_SCROLL  0xEC16
#define AFX_TIMER_ID_MENUBAR_POPUP      0xEC17
#define AFX_TIMER_ID_MENUBAR_REMOVE     0xEC18
#define AFX_TIMER_ID_RIBBONBAR_AUTO_COMMAND 0xEC19
#define AFX_TIMER_ID_RIBBONBAR_SHOW_KEYTIPS 0xEC1A
#define AFX_TIMER_ID_RIBBONPANEL_POPUP  0xEC1B
#define AFX_TIMER_ID_RIBBONPANEL_REMOVE 0xEC1C
#define AFX_TIMER_ID_RIBBONPANEL_AUTO_COMMAND 0xEC1D
#define AFX_TIMER_ID_LAST               0xEC1F
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_DESKACCESSORY           0xEFDA
#define AFX_IDS_OPENFILE                0xF000
#define AFX_IDS_SAVEFILE                0xF001
#define AFX_IDS_ALLFILTER               0xF002
#define AFX_IDS_UNTITLED                0xF003
#define AFX_IDS_SAVEFILECOPY            0xF004
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define AFX_IDS_UNNAMED_FILE            0xF006
#define AFX_IDS_HIDE                    0xF011
#define AFX_IDP_NO_ERROR_AVAILABLE      0xF020
#define AFX_IDS_NOT_SUPPORTED_EXCEPTION 0xF021
#define AFX_IDS_RESOURCE_EXCEPTION      0xF022
#define AFX_IDS_MEMORY_EXCEPTION        0xF023
#define AFX_IDS_USER_EXCEPTION          0xF024
#define AFX_IDS_INVALID_ARG_EXCEPTION   0xF025
#define AFX_IDS_PRINTONPORT             0xF040
#define AFX_IDS_ONEPAGE                 0xF041
#define AFX_IDS_TWOPAGE                 0xF042
#define AFX_IDS_PRINTPAGENUM            0xF043
#define AFX_IDS_PREVIEWPAGEDESC         0xF044
#define AFX_IDS_PRINTDEFAULTEXT         0xF045
#define AFX_IDS_PRINTDEFAULT            0xF046
#define AFX_IDS_PRINTFILTER             0xF047
#define AFX_IDS_PRINTCAPTION            0xF048
#define AFX_IDS_PRINTTOFILE             0xF049
#define AFX_IDS_OBJECT_MENUITEM         0xF080
#define AFX_IDS_EDIT_VERB               0xF081
#define AFX_IDS_ACTIVATE_VERB           0xF082
#define AFX_IDS_CHANGE_LINK             0xF083
#define AFX_IDS_AUTO                    0xF084
#define AFX_IDS_MANUAL                  0xF085
#define AFX_IDS_FROZEN                  0xF086
#define AFX_IDS_ALL_FILES               0xF087
#define AFX_IDS_SAVE_MENU               0xF088
#define AFX_IDS_UPDATE_MENU             0xF089
#define AFX_IDS_SAVE_AS_MENU            0xF08A
#define AFX_IDS_SAVE_COPY_AS_MENU       0xF08B
#define AFX_IDS_EXIT_MENU               0xF08C
#define AFX_IDS_UPDATING_ITEMS          0xF08D
#define AFX_IDS_METAFILE_FORMAT         0xF08E
#define AFX_IDS_DIB_FORMAT              0xF08F
#define AFX_IDS_BITMAP_FORMAT           0xF090
#define AFX_IDS_LINKSOURCE_FORMAT       0xF091
#define AFX_IDS_EMBED_FORMAT            0xF092
#define AFX_IDS_PASTELINKEDTYPE         0xF094
#define AFX_IDS_UNKNOWNTYPE             0xF095
#define AFX_IDS_RTF_FORMAT              0xF096
#define AFX_IDS_TEXT_FORMAT             0xF097
#define AFX_IDS_INVALID_CURRENCY        0xF098
#define AFX_IDS_INVALID_DATETIME        0xF099
#define AFX_IDS_INVALID_DATETIMESPAN    0xF09A
#define AFX_IDP_INVALID_FILENAME        0xF100
#define AFX_IDP_FAILED_TO_OPEN_DOC      0xF101
#define AFX_IDP_FAILED_TO_SAVE_DOC      0xF102
#define AFX_IDP_ASK_TO_SAVE             0xF103
#define AFX_IDP_FAILED_TO_CREATE_DOC    0xF104
#define AFX_IDP_FILE_TOO_LARGE          0xF105
#define AFX_IDP_FAILED_TO_START_PRINT   0xF106
#define AFX_IDP_FAILED_TO_LAUNCH_HELP   0xF107
#define AFX_IDP_INTERNAL_FAILURE        0xF108
#define AFX_IDP_COMMAND_FAILURE         0xF109
#define AFX_IDP_FAILED_MEMORY_ALLOC     0xF10A
#define AFX_IDP_UNREG_DONE              0xF10B
#define AFX_IDP_UNREG_FAILURE           0xF10C
#define AFX_IDP_DLL_LOAD_FAILED         0xF10D
#define AFX_IDP_DLL_BAD_VERSION         0xF10E
#define AFX_IDP_PARSE_INT               0xF110
#define AFX_IDP_PARSE_REAL              0xF111
#define AFX_IDP_PARSE_INT_RANGE         0xF112
#define AFX_IDP_PARSE_REAL_RANGE        0xF113
#define AFX_IDP_PARSE_STRING_SIZE       0xF114
#define AFX_IDP_PARSE_RADIO_BUTTON      0xF115
#define AFX_IDP_PARSE_BYTE              0xF116
#define AFX_IDP_PARSE_UINT              0xF117
#define AFX_IDP_PARSE_DATETIME          0xF118
#define AFX_IDP_PARSE_CURRENCY          0xF119
#define AFX_IDP_PARSE_GUID              0xF11A
#define AFX_IDP_PARSE_TIME              0xF11B
#define AFX_IDP_PARSE_DATE              0xF11C
#define AFX_IDP_FAILED_INVALID_FORMAT   0xF120
#define AFX_IDP_FAILED_INVALID_PATH     0xF121
#define AFX_IDP_FAILED_DISK_FULL        0xF122
#define AFX_IDP_FAILED_ACCESS_READ      0xF123
#define AFX_IDP_FAILED_ACCESS_WRITE     0xF124
#define AFX_IDP_FAILED_IO_ERROR_READ    0xF125
#define AFX_IDP_FAILED_IO_ERROR_WRITE   0xF126
#define AFX_IDP_SCRIPT_ERROR            0xF130
#define AFX_IDP_SCRIPT_DISPATCH_EXCEPTION 0xF131
#define AFX_IDP_STATIC_OBJECT           0xF180
#define AFX_IDP_FAILED_TO_CONNECT       0xF181
#define AFX_IDP_SERVER_BUSY             0xF182
#define AFX_IDP_BAD_VERB                0xF183
#define AFX_IDS_NOT_DOCOBJECT           0xF184
#define AFX_IDP_FAILED_TO_NOTIFY        0xF185
#define AFX_IDP_FAILED_TO_LAUNCH        0xF186
#define AFX_IDP_ASK_TO_UPDATE           0xF187
#define AFX_IDP_FAILED_TO_UPDATE        0xF188
#define AFX_IDP_FAILED_TO_REGISTER      0xF189
#define AFX_IDP_FAILED_TO_AUTO_REGISTER 0xF18A
#define AFX_IDP_FAILED_TO_CONVERT       0xF18B
#define AFX_IDP_GET_NOT_SUPPORTED       0xF18C
#define AFX_IDP_SET_NOT_SUPPORTED       0xF18D
#define AFX_IDP_ASK_TO_DISCARD          0xF18E
#define AFX_IDP_FAILED_TO_CREATE        0xF18F
#define AFX_IDP_FAILED_MAPI_LOAD        0xF190
#define AFX_IDP_INVALID_MAPI_DLL        0xF191
#define AFX_IDP_FAILED_MAPI_SEND        0xF192
#define AFX_IDP_FILE_NONE               0xF1A0
#define AFX_IDP_FILE_GENERIC            0xF1A1
#define AFX_IDP_FILE_NOT_FOUND          0xF1A2
#define AFX_IDP_FILE_BAD_PATH           0xF1A3
#define AFX_IDP_FILE_TOO_MANY_OPEN      0xF1A4
#define AFX_IDP_FILE_ACCESS_DENIED      0xF1A5
#define AFX_IDP_FILE_INVALID_FILE       0xF1A6
#define AFX_IDP_FILE_REMOVE_CURRENT     0xF1A7
#define AFX_IDP_FILE_DIR_FULL           0xF1A8
#define AFX_IDP_FILE_BAD_SEEK           0xF1A9
#define AFX_IDP_FILE_HARD_IO            0xF1AA
#define AFX_IDP_FILE_SHARING            0xF1AB
#define AFX_IDP_FILE_LOCKING            0xF1AC
#define AFX_IDP_FILE_DISKFULL           0xF1AD
#define AFX_IDP_FILE_EOF                0xF1AE
#define AFX_IDP_ARCH_NONE               0xF1B0
#define AFX_IDP_ARCH_GENERIC            0xF1B1
#define AFX_IDP_ARCH_READONLY           0xF1B2
#define AFX_IDP_ARCH_ENDOFFILE          0xF1B3
#define AFX_IDP_ARCH_WRITEONLY          0xF1B4
#define AFX_IDP_ARCH_BADINDEX           0xF1B5
#define AFX_IDP_ARCH_BADCLASS           0xF1B6
#define AFX_IDP_ARCH_BADSCHEMA          0xF1B7
#define AFX_IDS_OCC_SCALEUNITS_PIXELS   0xF1C0
#define AFX_IDS_STATUS_FONT             0xF230
#define AFX_IDS_TOOLTIP_FONT            0xF231
#define AFX_IDS_UNICODE_FONT            0xF232
#define AFX_IDS_MINI_FONT               0xF233
#define AFX_IDP_SQL_CONNECT_FAIL        0xF281
#define AFX_IDP_SQL_RECORDSET_FORWARD_ONLY 0xF282
#define AFX_IDP_SQL_EMPTY_COLUMN_LIST   0xF283
#define AFX_IDP_SQL_FIELD_SCHEMA_MISMATCH 0xF284
#define AFX_IDP_SQL_ILLEGAL_MODE        0xF285
#define AFX_IDP_SQL_MULTIPLE_ROWS_AFFECTED 0xF286
#define AFX_IDP_SQL_NO_CURRENT_RECORD   0xF287
#define AFX_IDP_SQL_NO_ROWS_AFFECTED    0xF288
#define AFX_IDP_SQL_RECORDSET_READONLY  0xF289
#define AFX_IDP_SQL_SQL_NO_TOTAL        0xF28A
#define AFX_IDP_SQL_ODBC_LOAD_FAILED    0xF28B
#define AFX_IDP_SQL_DYNASET_NOT_SUPPORTED 0xF28C
#define AFX_IDP_SQL_SNAPSHOT_NOT_SUPPORTED 0xF28D
#define AFX_IDP_SQL_API_CONFORMANCE     0xF28E
#define AFX_IDP_SQL_SQL_CONFORMANCE     0xF28F
#define AFX_IDP_SQL_NO_DATA_FOUND       0xF290
#define AFX_IDP_SQL_ROW_UPDATE_NOT_SUPPORTED 0xF291
#define AFX_IDP_SQL_ODBC_V2_REQUIRED    0xF292
#define AFX_IDP_SQL_NO_POSITIONED_UPDATES 0xF293
#define AFX_IDP_SQL_LOCK_MODE_NOT_SUPPORTED 0xF294
#define AFX_IDP_SQL_DATA_TRUNCATED      0xF295
#define AFX_IDP_SQL_ROW_FETCH           0xF296
#define AFX_IDP_SQL_INCORRECT_ODBC      0xF297
#define AFX_IDP_SQL_UPDATE_DELETE_FAILED 0xF298
#define AFX_IDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED 0xF299
#define AFX_IDP_SQL_FIELD_NOT_FOUND     0xF29A
#define AFX_IDP_SQL_BOOKMARKS_NOT_SUPPORTED 0xF29B
#define AFX_IDP_SQL_BOOKMARKS_NOT_ENABLED 0xF29C
#define AFX_IDS_DELETED                 0xF29D
#define AFX_IDP_DAO_ENGINE_INITIALIZATION 0xF2B0
#define AFX_IDP_DAO_DFX_BIND            0xF2B1
#define AFX_IDP_DAO_OBJECT_NOT_OPEN     0xF2B2
#define AFX_IDP_DAO_ROWTOOSHORT         0xF2B3
#define AFX_IDP_DAO_BADBINDINFO         0xF2B4
#define AFX_IDP_DAO_COLUMNUNAVAILABLE   0xF2B5
#define AFX_IDS_HTTP_TITLE              0xF2D1
#define AFX_IDS_HTTP_NO_TEXT            0xF2D2
#define AFX_IDS_HTTP_BAD_REQUEST        0xF2D3
#define AFX_IDS_HTTP_AUTH_REQUIRED      0xF2D4
#define AFX_IDS_HTTP_FORBIDDEN          0xF2D5
#define AFX_IDS_HTTP_NOT_FOUND          0xF2D6
#define AFX_IDS_HTTP_SERVER_ERROR       0xF2D7
#define AFX_IDS_HTTP_NOT_IMPLEMENTED    0xF2D8
#define AFX_IDS_CHECKLISTBOX_UNCHECK    0xF2E1
#define AFX_IDS_CHECKLISTBOX_CHECK      0xF2E2
#define AFX_IDS_CHECKLISTBOX_MIXED      0xF2E3
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_1 0xF2E4
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_2 0xF2E5
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_3 0xF2E6
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_4 0xF2E7
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_5 0xF2E8
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_6 0xF2E9
#define AFX_IDS_AUTOSAVE_RECOVERED      0xF2EA
#define AFX_IDS_PROPPAGE_UNKNOWN        0xFE01
#define AFX_IDS_COLOR_DESKTOP           0xFE04
#define AFX_IDS_COLOR_APPWORKSPACE      0xFE05
#define AFX_IDS_COLOR_WNDBACKGND        0xFE06
#define AFX_IDS_COLOR_WNDTEXT           0xFE07
#define AFX_IDS_COLOR_MENUBAR           0xFE08
#define AFX_IDS_COLOR_MENUTEXT          0xFE09
#define AFX_IDS_COLOR_ACTIVEBAR         0xFE0A
#define AFX_IDS_COLOR_INACTIVEBAR       0xFE0B
#define AFX_IDS_COLOR_ACTIVETEXT        0xFE0C
#define AFX_IDS_COLOR_INACTIVETEXT      0xFE0D
#define AFX_IDS_COLOR_ACTIVEBORDER      0xFE0E
#define AFX_IDS_COLOR_INACTIVEBORDER    0xFE0F
#define AFX_IDS_COLOR_WNDFRAME          0xFE10
#define AFX_IDS_COLOR_SCROLLBARS        0xFE11
#define AFX_IDS_COLOR_BTNFACE           0xFE12
#define AFX_IDS_COLOR_BTNSHADOW         0xFE13
#define AFX_IDS_COLOR_BTNTEXT           0xFE14
#define AFX_IDS_COLOR_BTNHIGHLIGHT      0xFE15
#define AFX_IDS_COLOR_DISABLEDTEXT      0xFE16
#define AFX_IDS_COLOR_HIGHLIGHT         0xFE17
#define AFX_IDS_COLOR_HIGHLIGHTTEXT     0xFE18
#define AFX_IDS_REGULAR                 0xFE19
#define AFX_IDS_BOLD                    0xFE1A
#define AFX_IDS_ITALIC                  0xFE1B
#define AFX_IDS_BOLDITALIC              0xFE1C
#define AFX_IDS_SAMPLETEXT              0xFE1D
#define AFX_IDS_DISPLAYSTRING_FONT      0xFE1E
#define AFX_IDS_DISPLAYSTRING_COLOR     0xFE1F
#define AFX_IDS_DISPLAYSTRING_PICTURE   0xFE20
#define AFX_IDS_PICTUREFILTER           0xFE21
#define AFX_IDS_PICTYPE_UNKNOWN         0xFE22
#define AFX_IDS_PICTYPE_NONE            0xFE23
#define AFX_IDS_PICTYPE_BITMAP          0xFE24
#define AFX_IDS_PICTYPE_METAFILE        0xFE25
#define AFX_IDS_PICTYPE_ICON            0xFE26
#define AFX_IDS_COLOR_PPG               0xFE28
#define AFX_IDS_COLOR_PPG_CAPTION       0xFE29
#define AFX_IDS_FONT_PPG                0xFE2A
#define AFX_IDS_FONT_PPG_CAPTION        0xFE2B
#define AFX_IDS_PICTURE_PPG             0xFE2C
#define AFX_IDS_PICTURE_PPG_CAPTION     0xFE2D
#define AFX_IDS_PICTUREBROWSETITLE      0xFE30
#define AFX_IDS_BORDERSTYLE_0           0xFE31
#define AFX_IDS_BORDERSTYLE_1           0xFE32
#define AFX_IDS_VERB_EDIT               0xFE40
#define AFX_IDS_VERB_PROPERTIES         0xFE41
#define AFX_IDP_PICTURECANTOPEN         0xFE83
#define AFX_IDP_PICTURECANTLOAD         0xFE84
#define AFX_IDP_PICTURETOOLARGE         0xFE85
#define AFX_IDP_PICTUREREADFAILED       0xFE86
#define AFX_IDP_E_ILLEGALFUNCTIONCALL   0xFEA0
#define AFX_IDP_E_OVERFLOW              0xFEA1
#define AFX_IDP_E_OUTOFMEMORY           0xFEA2
#define AFX_IDP_E_DIVISIONBYZERO        0xFEA3
#define AFX_IDP_E_OUTOFSTRINGSPACE      0xFEA4
#define AFX_IDP_E_OUTOFSTACKSPACE       0xFEA5
#define AFX_IDP_E_BADFILENAMEORNUMBER   0xFEA6
#define AFX_IDP_E_FILENOTFOUND          0xFEA7
#define AFX_IDP_E_BADFILEMODE           0xFEA8
#define AFX_IDP_E_FILEALREADYOPEN       0xFEA9
#define AFX_IDP_E_DEVICEIOERROR         0xFEAA
#define AFX_IDP_E_FILEALREADYEXISTS     0xFEAB
#define AFX_IDP_E_BADRECORDLENGTH       0xFEAC
#define AFX_IDP_E_DISKFULL              0xFEAD
#define AFX_IDP_E_BADRECORDNUMBER       0xFEAE
#define AFX_IDP_E_BADFILENAME           0xFEAF
#define AFX_IDP_E_TOOMANYFILES          0xFEB0
#define AFX_IDP_E_DEVICEUNAVAILABLE     0xFEB1
#define AFX_IDP_E_PERMISSIONDENIED      0xFEB2
#define AFX_IDP_E_DISKNOTREADY          0xFEB3
#define AFX_IDP_E_PATHFILEACCESSERROR   0xFEB4
#define AFX_IDP_E_PATHNOTFOUND          0xFEB5
#define AFX_IDP_E_INVALIDPATTERNSTRING  0xFEB6
#define AFX_IDP_E_INVALIDUSEOFNULL      0xFEB7
#define AFX_IDP_E_INVALIDFILEFORMAT     0xFEB8
#define AFX_IDP_E_INVALIDPROPERTYVALUE  0xFEB9
#define AFX_IDP_E_INVALIDPROPERTYARRAYINDEX 0xFEBA
#define AFX_IDP_E_SETNOTSUPPORTEDATRUNTIME 0xFEBB
#define AFX_IDP_E_SETNOTSUPPORTED       0xFEBC
#define AFX_IDP_E_NEEDPROPERTYARRAYINDEX 0xFEBD
#define AFX_IDP_E_SETNOTPERMITTED       0xFEBE
#define AFX_IDP_E_GETNOTSUPPORTEDATRUNTIME 0xFEBF
#define AFX_IDP_E_GETNOTSUPPORTED       0xFEC0
#define AFX_IDP_E_PROPERTYNOTFOUND      0xFEC1
#define AFX_IDP_E_INVALIDCLIPBOARDFORMAT 0xFEC2
#define AFX_IDP_E_INVALIDPICTURE        0xFEC3
#define AFX_IDP_E_PRINTERERROR          0xFEC4
#define AFX_IDP_E_CANTSAVEFILETOTEMP    0xFEC5
#define AFX_IDP_E_SEARCHTEXTNOTFOUND    0xFEC6
#define AFX_IDP_E_REPLACEMENTSTOOLONG   0xFEC7


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        281
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1309
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
